### ISSUE TITLE
Golan Heights aircraft explode on Server Launch

### ISSUE THREAD

**Issue by gabe88w** [dcs-liberation/dcs_liberation#3364] opened 2024-03-27 00:14 UTC
### Affected versions

10.0.0, Development build

### Build information

DCS Liberation 11.0.0 & 10.0.0

### Description

 I'm starting a Syria liberation campaign on the Golan Heights and every time I launch and join my dedicated server basically all the aircraft just explode and die except for mine. I tried launching the mission in SP and no issues there so not sure what the issue is.

Error on Server:

ERROR  SCRIPTING  Mission script error: [string "C:\Users\luck\AppData\Local\Temp\Fox3-0766/~mis00004FEA.lua"]:154: Unit doesn't exist stack traceback: [C]: ? [C]: in function 'getLife' [string "C:\Users\luck\AppData\Local\Temp\Fox3-0766/~mis00004FEA.lua"]:154: in function <[string "C:\Users\luck\AppData\Local\Temp\Fox3-0766/~mis00004FEA.lua"]:151>

This happens on 10.0.0 build and preview build. 

I attached the liberation save zip, inside is also the .miz file.

### Save game and other files (save game required, bugs without saves will be closed)

[state (2).json](https://github.com/dcs-liberation/dcs_liberation/files/14765870/state.2.json)
[golan.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/14765871/golan.liberation.zip)

**Comment by Starfire13** [comment] 2024-03-27 09:57
If it works in singleplayer but not in multiplayer, then that sounds like a DCS server problem. There is no difference between a Liberation file meant for singleplayer and one meant for multiplayer.

1. Does this happen consistently on this miz file if you run it multiple times on this server?

2. If so, does this happen on every single Liberation-generated mission on this server?

3. If so, does it happen in other non-Liberation generated missions on this server?

4. Does that error only show up in the server log if all the planes explode?

**Comment by zhexu14** [comment] 2024-04-08 11:19
The error looks like a side effect of whatever caused the units to explode and not the cause. Do you have the full log?

I tried running your save game but it didn't have any player or client slots. After adding a player slot on a unit, the save worked fine on a dedicated server.

**Comment by zhexu14** [comment] 2024-10-06 05:03
Closing this issue as as it seems to be a DCS issue.

**Closed as completed by zhexu14** 2024-10-06 05:03 UTC
Labels: bug
