### ISSUE TITLE
Antiship target culled

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#1761] opened 2021-11-17 00:12 UTC
Liberation vers 6.0-3026

Operation Allied Sword on Syria, default factions, 1985 preset with weapons restriction

Tasked an antiship weapon against a far northern group of two enemy ships with culling enabled at 100 km, appears to have been culled despite being a target

[allied sword 3026.zip](https://github.com/dcs-liberation/dcs_liberation/files/7550684/allied.sword.3026.zip)
campaign file and .miz attached

I did have "fast forward to first contact" option enabled but i dunno if that affects anything

The culled target is objective SALAMANDER

**Comment by DanAlbert** [comment] 2022-01-16 21:53
Duplicate of https://github.com/dcs-liberation/dcs_liberation/issues/1034

**Closed as completed by DanAlbert** 2022-01-16 21:53 UTC
Labels: bug
