### ISSUE TITLE
Unit deaths not tracked?

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#904] opened 2021-02-20 05:17 UTC
**Describe the bug**
Ran a mission and all but one unit death was applied on "Accept Results".  On the following screen it was shown that there were no red/blue losses.

**To Reproduce**
1. Start liberation
2. Generate Mission
3. Start DCS
4. Play mission

**Expected behavior**
Most/All unit deaths should appear in the "Debriefing" screen.

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

[UnitDeathsNotTracked.zip](https://github.com/Khopa/dcs_liberation/files/6014163/UnitDeathsNotTracked.zip)

Included:
- Campaign (pre mission)
- Mission
- State.json
- DCS Debriefing Log
- Liberation Console Output

**Version information (please complete the following information):**
 - DCS Liberation 2.4.2

**Additional context**
The State.json looks like it's probably correct.

If I reload the campaign in Liberation, take off, then immediately submit the state.json, things look ok.

I started Liberation kinda weird.  Started two instances accidentally, then closed both terminals before the UI started (so no UI appeared).  Then after both terminals closed I started Liberation for the last time.

**Comment by DanAlbert** [comment] 2021-02-20 07:51
To clarify: the UI is wrong an the behavior is correct?

**Comment by SnappyComebacks** [comment] 2021-02-20 16:36
Both the UI and the Campaign state (inventories of planes and ground units at airfields) did not update.  The front line did not progress either.

When reloading the campaign and manually applying the state by doing "Take off" then immediately manually submitting, the front line will move.

**Comment by DanAlbert** [comment] 2021-02-20 20:47
Might be a dup of https://github.com/Khopa/dcs_liberation/issues/886

**Comment by SnappyComebacks** [comment] 2021-02-20 22:24
I'll see if I can capture the same error as Starfire13 reports from that ticket.

**Comment by DanAlbert** [comment] 2021-02-20 23:36
Pretty sure we already have the data we need. No one has had time to look.

**Comment by DanAlbert** [comment] 2021-04-10 23:23
We still weren't able to reproduce that one, but idk if it's related or not.

Having finally been able to look at this, I'm now wondering if I misunderstood the report. Everything here looks pretty normal to me:
![image](https://user-images.githubusercontent.com/315852/114287030-984ce180-9a18-11eb-8977-025f5561150c.png)

Of course, hard to eyeball what might be wrong here.

Note that infantry deaths are not tracked because they have no impact on the campaign. Is that what you're thinking of?

> Ran a mission and all but one unit death was applied on "Accept Results".

I'm probably way too late asking this question for you to remember, but can you be more specific? Is there something I should be looking for?

**Comment by DanAlbert** [comment] 2021-04-21 10:05
Closing since everything looks fine here, but easy to reopen if someone can point out the problem.

**Closed as completed by DanAlbert** 2021-04-21 10:05 UTC
Labels: bug
