### ISSUE TITLE
Aircraft spawning at specific parking slots in cold start actually start in flight and crash.

### ISSUE THREAD

**Issue by Lordeath19** [dcs-liberation/dcs_liberation#2782] opened 2023-04-11 13:41 UTC
### Affected versions

6.1.1

### Build information

Doesn't matter what build. tested on local dev with multiple versions

### Description

Looking at the aircraft generation, for example in the following mission. We can see that the flankers at aleppo have took the parking slot "H01" and "H02" with the supposed takeoff from ramp. Upon careful inspection, the aircraft are actually spawned in air in a "turning point" waypoint type. this causes them to crash immediately at mission start.
A symptom that can also happen is that the aircraft are spawned above the runway in a single point. causing all of them to spawn and combust.

My theory is that in syria, falklands, persian gulf and nevada there are "Heli parking slots". planes spawned there automatically turn into turning point and thus the issue is created.

I am not sure if the fix should be in pydcs or somewhere else, but this causes the enemy AI to always die above a certain aircraft count in aleppo.

Could also be fixed by regarding the `airplanes` parameter in the parking slot object.

### Save game and other files

[liberation_nextturn_miz.zip](https://github.com/dcs-liberation/dcs_liberation/files/11200943/liberation_nextturn_miz.zip)

**Comment by Starfire13** [comment] 2023-04-11 21:53
Duplicate of #371

**Comment by Starfire13** [comment] 2023-04-11 22:31
Essentially, Liberation does not know if a parking spot is large or small or helicopter only. That information isn't available from Pydcs (or didn't use to be at least, unless that's changed in the past 2 years), so until Pydcs exposes that information, this problem will keep occurring. It typically happens on a few specific airfields; there are two on the Syria map that are repeat offenders and we regularly get reports about them from players.

**Comment by Lordeath19** [comment] 2023-04-14 10:48
Fixed in pydcs https://github.com/pydcs/dcs/pull/294, just need to update pydcs reference.

**Comment by DanAlbert** [comment] 2023-04-14 18:13
Keep in mind that it won't be a complete fix. Every other time this bug has been reported, it's been a big plane spawning in a HAS. The parking property for shelters is unfortunately not set by DCS, so those will still be broken :(

Having it fixed for helicopter slots will still be good though 👍

**Closed as completed** 2023-04-15 20:47 UTC
Labels: bug
