### ISSUE TITLE
unsupported operand type(s) for +=: 'SafeLoader' and 'int'

### ISSUE THREAD

**Issue by eerturk** [dcs-liberation/dcs_liberation#2776] opened 2023-04-05 03:23 UTC
### Affected versions

6.1.1

### Description

I am having the following issue while I am trying to start a new game.

![error](https://user-images.githubusercontent.com/5462386/229972740-4b6b49ee-cf91-4315-8e76-05d18ca416e9.JPG)

When I click new game again, Liberation app crashes.

### Save game and other files

![error](https://user-images.githubusercontent.com/5462386/229973415-f3da08d4-b4a9-4702-849c-3aae11feb871.JPG)

**Comment by eerturk** [comment] 2023-04-05 03:24
[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/11154872/liberation.log)
 
Here is the log as well.

**Comment by DanAlbert** [comment] 2023-04-05 06:09
There's a different bug template for "new game failed" 
![image](https://user-images.githubusercontent.com/315852/229995164-c85204e8-4768-4124-b484-147543c938ba.png)

The error says you have a busted campaign file that failed to parse. Almost certainly a custom one because otherwise everyone would have hit this.

**Comment by DanAlbert** [comment] 2023-04-06 00:15
The log says it failed while loading Vectron's Claw:

```
2023-04-04 23:22:26,385 :: root :: DEBUG :: Loading campaign from resources\campaigns\operation_vectrons_claw.yaml...
```

Have you modified that campaign? If so, we need to see the modifications you made (upload the whole file).

If not, your install is probably corrupt. Delete liberation, redownload, extract again.

If it's *still* broken, I'm out of guesses as to what is different between your environment and every other player's.

The error here is strange, fwiw. It's not the normal parse error. The fact that no one else is hitting this does strongly suggest that it's either something wrong in your liberation install or in your environment.

Closing since there isn't enough information in the bug for us to investigate. We do already ignore the typical errors from campaign parsing, and I'm not comfortable ignoring `TypeError` here because that's likely to hide real bugs as well. If you can give instructions for how we could reproduce this error ourselves, we can reopen, but there's no action we can take with what we have.

**Closed as not planned by DanAlbert** 2023-04-06 00:15 UTC
Labels: bug
