### ISSUE TITLE
Picklists Display Improperly, Rendered Unusable

### ISSUE THREAD

**Issue by dproko** [dcs-liberation/dcs_liberation#1168] opened 2021-06-01 13:01 UTC
I've just installed v2.5.1, and the option picklists are too large for me to select, thus unusable.  I have checkboxes, and they work fine.  The help text is also unusually large.  I've rebooted and tried different scaling, with no luck.  See pictures.

I can reproduce it simply by starting the application.  

![2021-05-30 (14)](https://user-images.githubusercontent.com/85173071/120327481-abed2980-c29e-11eb-8764-7e6c77ce7a78.png)
![2021-05-30 (15)](https://user-images.githubusercontent.com/85173071/120327487-ac85c000-c29e-11eb-9dc6-2b620cbe0cc3.png)

**Comment by DanAlbert** [comment] 2021-06-05 02:21
Duplicate of #887

**Closed as completed by DanAlbert** 2021-06-05 02:21 UTC
Labels: bug, UX
