### ISSUE TITLE
AI planes spawn intersecting mid-air at Khalkhalah

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#518] opened 2020-12-06 18:40 UTC
When doing the "Golan Heights Battle" campaign (Winter Modern, Player: USA 1990, Enemy: Syria 1982), planes spawn midair intersecting with each other at Khalkhalah.  Several enemy planes crash within a few seconds of starting the mission.  This happens within multiple missions.

There are three planes in this photo.
![Overlapping_clean](https://user-images.githubusercontent.com/74509817/101289053-415ba500-37b7-11eb-92b4-ef24242acfdc.png)

**Comment by DanAlbert** [comment] 2020-12-06 19:59
Already fixed in the dev build. If it's still present it's a map bug that we can't fix.

**Closed as completed by DanAlbert** 2020-12-06 19:59 UTC

**Comment by MedievalBunny** [comment] 2020-12-21 20:28
I'm having this problem as well on the current build of 2.3.2

It appears so though aircraft are attempting to spawn on the helicopter pads starting with H01, but the spawn waypoint is set to Turning Point and the aircraft end up spawning in on top of each other. 

It may well be a map issue in DCS, when I set the spawn type to Ramp Start they jump to a completely different airbase. I'm on Stable as well, so this may be fixed on Open Beta. But I figured I'd offer some more info in case it's helpful. I attached a .miz where the problem is occurring. 
[liberation_nextturn_crash.zip](https://github.com/Khopa/dcs_liberation/files/5726356/liberation_nextturn_crash.zip)

**Comment by Mustang-25** [comment] 2021-04-29 00:27
I'm play testing a new custom campaign and this is still an issue. They are trying to spawn in the helo slots and end up airspawning on top of each other again.
