### ISSUE TITLE
Aircraft missing from Air Wing Inventory but still exists in Airbase Inventory

### ISSUE THREAD

**Issue by clericneokun** [dcs-liberation/dcs_liberation#1880] opened 2021-12-30 07:41 UTC
### Affected versions

5.0.0

### Description

**Bug:**

- E3 AWACS of the 960th AAC Squadron disappeared from the Air Wing Inventory but still exists in the Kutaisi AFB Inventory. 

**To Reproduce:**

- Unknown. Save file attached should still show the inventory discrepancies.

**Add'l Info:**

- Aircraft was not destroyed during the previous turn.
- Campaign is being run from a local machine.

### Save game and other files

[Liberation and State Json File.zip](https://github.com/dcs-liberation/dcs_liberation/files/7791901/Liberation.and.State.Json.File.zip)

**Comment by Starfire13** [comment] 2021-12-30 08:51
To add on, a similar issue has been reported multiple times on Discord by folks running a server (passing turn is a workaround because the aircraft appears on the next turn), but I believe this is the first instance of it occuring in singleplayer. It appears that the aircraft is missing from the Inventory pane in Air Wing, but it correctly shown to be available when clicking on the airfield itself.

**Comment by Starfire13** [comment] 2022-01-10 10:20
I have an example here where the 91 aircraft at Nellis have gone missing after a couple of saves. Note that both saves are for Turn 10. There has been no reading of the state.json between the two files. It is the exact same turn. One is saved prior to planning, the other is saved after planning.

[Saves.zip](https://github.com/dcs-liberation/dcs_liberation/files/7838104/Saves.zip)

**Comment by pwmohr** [comment] 2022-05-09 18:21
I have had this same problem. Several aircraft show up in the airport inventories (which appear correct to me), but do not show up in the air wing inventory list and are not available for tasking. In this example, at least 12 f/a-18's show up at Tonopah Test Range, and none show up in the air wing inventory.

[Save and State JSON files.zip](https://github.com/dcs-liberation/dcs_liberation/files/8654201/Save.and.State.JSON.files.zip)

**Comment by DanAlbert** [comment] 2022-10-15 21:59
Has anyone managed to work out repro instructions for this? To investigate I need to be able to reproduce the bug. From what I can tell, we have a lot of save games with a mix of before and after (usually both) states, but without any known way to transition between the two that will show the bug.

https://github.com/dcs-liberation/dcs_liberation/issues/2182 describes the steps that happened when that filer saw the bug, but I can't reproduce that in my own game.

Since I can't reproduce this issue, I think for now I have to assume that the bug has been fixed by another change. I'm going to close this until someone can prove otherwise. FWIW, I have seen this issue before as well, but I haven't in quite some time, so I suspect the bug is actually gone and not just hard to repro.

**Closed as not planned by DanAlbert** 2022-10-15 21:59 UTC
Labels: bug
