### ISSUE TITLE
CAS Missions waypoints has a takeoff waypoint instead of landing

### ISSUE THREAD

**Issue by FelipLemos** [dcs-liberation/dcs_liberation#2611] opened 2022-12-02 16:24 UTC
### Affected versions

6.0.0

### Description

Any frontline CAS missions auto generated has a second Takeoff waypoint instead of a Landing way point, this cause the aircrafts to crash instead of land. **This happens in any save.**

### Save game and other files

[bug.zip](https://github.com/dcs-liberation/dcs_liberation/files/10142673/bug.zip)
This has my Campaign file that I notice the bug, and the last state.json  
Although this can be reproduce in any save, any campaign

**Comment by Starfire13** [comment] 2022-12-02 21:50
The name of the waypoint is incorrect (which should be fixed but isn't the root of the problem). The problem is that the waypoint type for that waypoint is set to Turning Point instead of Landing.

**Comment by DanAlbert** [comment] 2022-12-04 00:13
> 6.0.0

You sure about that? This doesn't load.

**Closed as completed** 2022-12-04 00:30 UTC
Labels: bug
