### ISSUE TITLE
Allow players to create enemy tasking

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-liberation/dcs_liberation#1753] opened 2021-11-15 11:10 UTC
Before filing, please search the issue tracker to see if this feature has already been requested.

If requesting a DCS AI feature, check If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Is your feature request related to a problem? Please describe.**
I want to see the enemy tasking in the same manner that I can see my own. I also would like to create tasking for the enemy. A way to fight myself so to speak. 

**Describe the solution you'd like**
Even the default AI planner for friendly forces can't seem to keep tasking under 1 hour TOT. While a human player can easily create a 30-45 TOT mission. A mission full of CAP, CAS and misc strikes. If we're lucky the enemy gets up some CAP and basic CAS but is always easy to swat down by a good mission planner on the player side. 

It would be fun to fight ourselves on occasion by tasking everything blue and red.

**Additional context**
Can we see tasking now? Other than flight plans?

**Comment by DanAlbert** [comment] 2021-11-15 17:42
Duplicate of #1089

**Closed as completed by DanAlbert** 2021-11-15 17:42 UTC
Labels: enhancement
