### ISSUE TITLE
Logical Strike Targeting

### ISSUE THREAD

**Issue by nosv1** [dcs-liberation/dcs_liberation#2143] opened 2022-04-01 06:56 UTC
this is not the way...

**Is your feature request related to a problem? Please describe.**
The problem is if your strike target consists of more targets than your plane can carry bombs, then no matter how many planes you include in that flight, it's likely you leave a target behind - not very efficient.

**Describe the solution you'd like**
The solution is to mix the order of targets throughout the flight's planes. i.e. if there's a strike target with 6 targets and the planes are carrying 4 bombs (and we assume 1 bomb per target?) Plane 1 goes through the targets [1,2,3,4], Plane 2 starts at [5, 6, 1, 2] and so on, this should spread the bombing targets as much as possible. 

**Additional context**
I did some experimenting and yeh as it is now, if there's a 4 ship, but > 4 targets, each of em with have [1,2,3,4] as their first 4 bombing targets, but any extras are left untouched. It looks like all that was needed to update the bombing target order was to adjust which order you went through making the Bombing action

Below is where this takes place, I tried to see if it was possible to know the number of planes in the flight from this function, but I got lost tracing it back... also it'd be nice to know how many bombs were on the planes from within the function too (I think) - didn't look too hard to see how easy that was

![image](https://user-images.githubusercontent.com/47610393/161212797-f908c898-f9a2-4e43-bbba-7b1bccacd09d.png)

**Comment by DanAlbert** [comment] 2022-04-01 07:39
Duplicate of #1568

**Closed as completed by DanAlbert** 2022-04-01 07:39 UTC
Labels: enhancement
