### ISSUE TITLE
A10C no fuel

### ISSUE THREAD

**Issue by olivier28** [dcs-liberation/dcs_liberation#140] opened 2020-09-20 07:32 UTC
when I play in A10C I am obliged to put them in flight because whether it is in cold start, already started or on the runway, the planes have no fuel and when we ask for a refuel, the ground crew doesn't want to

**Comment by davidp57** [comment] 2020-09-28 18:46
I discussed with @olivier28 and we  could not reproduce the error.
@Khopa I suggest closing this one if nobody else had the same behavior.

**Comment by Khopa** [comment] 2020-09-29 17:49
I have also been unable to reproduce this issue; maybe the latest releases fixed it without us noticing. 

So i'll be closing this for now. 
But feel free to reopen should you encounter the issue again.

**Comment by unixwitch** [comment] 2020-10-22 07:42
i had this issue just now with 2.1.5: i started a new campaign, Syria - Invasion from Turkey, Bluefor modern vs PMC Russian.  after spawning at Hatay for a cold start, the aircraft (F/A-18C) had no fuel and ground crew wouldn't provide any.  in the mission editor, the airfield was configured to have no liquids available.

i've just gone to reproduce the problem and i can't - and it also doesn't happen with the save file that caused it before.  

i quit and restarted Liberation before trying to reproduce the problem; i wonder if that fixed it?  before starting this campaign, i had loaded another campaign on a different map (Caucasus) and didn't restart before creating the new one.

**Comment by unixwitch** [comment] 2020-10-30 15:39
#242 looks like another case of this issue, also on Syria.

cc @RampantCoyote

**Comment by DanAlbert** [comment] 2020-12-07 09:58
Most likely caused by the bug where we sometimes accidentally left airfields neutral, which has been fixed.

**Closed as completed by DanAlbert** 2020-12-07 09:58 UTC
