### ISSUE TITLE
RuntimeError: Duplicate TGO unit: BLUE|EWR|1|EWR

### ISSUE THREAD

**Issue by vanson77** [dcs-liberation/dcs_liberation#708] opened 2021-01-02 22:56 UTC
Unable to continue campaign because of "RuntimeError: Duplicate TGO unit: BLUE|EWR|1|EWR".
Immediately occured after capturing Base Anapa Vityazevo
Duplicate TGO errors happen quite regulary, but in case of EWR there is no possibility of selling and rebuying the unit to get around this error - therefore campaign is broken and cannot be continued. 4th campaign i had to abort because of this.

Traceback (most recent call last):
  File "qt_ui\widgets\QTopPanel.py", line 243, in launch_mission
  File "game\game.py", line 209, in initiate_event
  File "game\event\event.py", line 58, in generate
  File "game\operation\operation.py", line 307, in generate
  File "game\operation\operation.py", line 275, in _generate_ground_units
  File "gen\groundobjectsgen.py", line 429, in generate
  File "gen\groundobjectsgen.py", line 94, in generate
  File "gen\groundobjectsgen.py", line 110, in _register_unit_group
  File "game\unitmap.py", line 104, in add_ground_object_units
RuntimeError: Duplicate TGO unit: BLUE|EWR|1|EWR

Development Build 939

[black_sea_925.zip](https://github.com/Khopa/dcs_liberation/files/5760968/black_sea_925.zip)

**Comment by DanAlbert** [comment] 2021-01-03 01:14
> Duplicate TGO errors happen quite regulary

File them whenever you see them. This is the first we've heard of it in almost a month so we thought they were all fixed.

**Comment by Starfire13** [comment] 2021-01-04 01:02
I've had the same error back to back in 2 campaigns on build 939. It's preventing me from completing any campaigns.

**Comment by walterroach** [comment] 2021-01-04 17:29
This is caused by TGO IDs being reset each press of takeoff- after base capture event new TGOs are created providing a chance for name conflict.  Looks like I misunderstood how the frontline unit SHORAD get their IDs, and that reset isn't necessary at all.  I'm testing a fix for this now and should be uploading later.

**Closed as completed** 2021-01-04 17:36 UTC
Labels: bug
