### ISSUE TITLE
assign player cruising altitude

### ISSUE THREAD

**Issue by HILOK** [dcs-liberation/dcs_liberation#1166] opened 2021-06-01 09:55 UTC
i know there are other threads around that topic, but couldnt find a specific match -sorry if duplicate

**Is your feature request related to a problem? Please describe.**
default cruising altitude is set to 20000ft. if the player wishes to change that in DCS's ME, it requires several edits (all affected WYP for all affected flights) and creates mission timing and kneeboard issues

**Describe the solution you'd like**
add a new button/function in "Edit flight", e.g. pic below. this would only affect cruising waypoints (highlighted in the pic). recalculate mission timings and update kneeboard accordingly
![lib assign CRZ ALT](https://user-images.githubusercontent.com/76898536/120303809-7b71b380-c2cf-11eb-9978-d46ff541de0d.JPG)

**Additional context**
thanks for all your amazing work !!

**Comment by DanAlbert** [comment] 2021-06-01 09:57
Duplicate of #270

**Closed as completed by DanAlbert** 2021-06-01 09:57 UTC
Labels: enhancement
