### ISSUE TITLE
Default Altitudes for Helo CAS/Air Assault

### ISSUE THREAD

**Issue by rhoadsy123** [dcs-liberation/dcs_liberation#3249] opened 2023-11-18 20:41 UTC
**Is your feature request related to a problem? Please describe.**
Default altitudes for helicopter Air Assault/CAS flights cause them to do this very strange ground avoidance dance for a flight path. CAS flights will sometimes hit the ground, and most of the time don't really ever fire at anything. Air assault flights take extremely long times to reach their targets because they barely move forward. You can change the altitudes for friendly flights in the campaign UI to work around this issue, but the enemy flights are subjected to these problems.

**Describe the solution you'd like**
Change the default altitudes for these taskings to 500ft AGL. I've found that this altitude still keeps the flight low (Looking cool/avoiding air defenses/flying how helos would actually fly), but it keeps the flights away from terrain enough to not do the dance and fly normally.

**Comment by DanAlbert** [comment] 2023-11-18 22:02
Duplicate of #270

**Closed as not planned by DanAlbert** 2023-11-18 22:02 UTC
Labels: enhancement
