### ISSUE TITLE
Preview image on the campaign selector screen

### ISSUE THREAD

**Issue by cirmi00** [dcs-liberation/dcs_liberation#1253] opened 2021-06-18 10:19 UTC
Hi guys, 

First, liberation is still amazing. Thank you all for your hard work.

Would it be possible to get a small preview image on the campaign selector screen? When we are starting a new campaign, we need to generate most of the campaigns to see which one would be the best for us. Something like this would be great:

![image](https://user-images.githubusercontent.com/72670020/122546327-205df180-d02f-11eb-802a-47aa224d9c20.png)

This would help us to see which scenario is the most fitting for the type of campaign we want to play. It can be of course a static image coming from the campaign creator, it doesn't need to be dynamically generated or anything.

Thanks!

**Comment by cirmi00** [comment] 2021-06-18 10:23
Or maybe hidden behind a "PREVIEW" button or something which opens the image in a larger window... You get the idea I think.

**Comment by DanAlbert** [comment] 2021-06-18 10:43
Duplicate of #446

**Closed as completed by DanAlbert** 2021-06-18 10:43 UTC
Labels: enhancement
