### ISSUE TITLE
Control Enemy Faction

### ISSUE THREAD

**Issue by Kreampuff100** [dcs-liberation/dcs_liberation#3260] opened 2023-11-24 15:39 UTC
Having no experience with what coding a program like this takes, I'm sure this request is probably monumental in nature. I view Liberation through the eyes of a Mission Planner. Liberation is a fast and efficient alternative to spending hours in the mission editor.

For my squadron, being able to have the same control over Enemy Flight Packages as you do over allied flight packages would be a really helpful feature. It would be cool if the enemy faction still automatically planned all of its packages, but there was a Tab or something to toggle over and manipulate the enemy factions flights the same way you can the allies.

This would allow mission planners to have specific red flights arrive at specific times. Which could make missions overall much more interesting for squadrons.

This feature also would allow for some interesting "Versus" type of play where one person in a squadron can act as red commander to make things as difficult as possible as the blue flights.

**Comment by Starfire13** [comment] 2023-11-24 21:00
Duplicate of #1089, #1753

**Closed as not planned** 2023-11-24 21:14 UTC
Labels: enhancement
