### ISSUE TITLE
Squadrons defined in the yml can have a starting number of airplanes

### ISSUE THREAD

**Issue by Schneefl0cke** [dcs-liberation/dcs_liberation#2744] opened 2023-02-24 10:33 UTC
What: Squadrons defined in the .yml of a campaign should have a property that defines the number of planes the AI/Player starts with, without having to buy them.

Why: 
1. To shape historical scenarios better and have more control over the ai procurement of planes at the start.

Future:
My vision would be that the same could be done for ground forces (when they are configurable in some sort of task force, just like squadrons are). Then it would be possible to recreate conflicts much better.

**Comment by DanAlbert** [comment] 2023-02-24 18:16
Duplicate of #1583

**Closed as not planned by DanAlbert** 2023-02-24 18:16 UTC
Labels: enhancement
