### ISSUE TITLE
Fastforward DEAD skips mission, moves to SPLIT waypoint

### ISSUE THREAD

**Issue by magnuscodes** [dcs-liberation/dcs_liberation#3163] opened 2023-08-27 15:23 UTC
### Affected versions

8.1.0

### Description

Using the latest stable version of DCS Liberation, I generated a mission and set it up the way I like.

I created a package consisting of:
1 x F/A-18C SEAD
1 x F-16 DEAD
1 x F-15C Escort

I am using the fast-forward feature which skips to roughly the point of take-off for this package. I observed the SEAD package correctly engaging the SA-6 track radar and knocking it out.

The escort does its job, whacking a couple of MiGs on the path.

The F-16 however goes to the JOIN waypoint, skips INGRESS & the mission, and goes to SPLIT.

Attaching the mission file so you can have a look, see DEAD Sardine.

### Save game and other files (save game required, bugs without saves will be closed)

Mission file: [syria.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/12448301/syria.liberation.zip)

**Comment by Starfire13** [comment] 2023-08-27 20:25
Duplicate of #2802.

**Closed as not planned** 2023-09-21 02:44 UTC
Labels: bug
