### ISSUE TITLE
Adjustment/optimization of automatic investment in ground forces

### ISSUE THREAD

**Issue by slubbermand** [dcs-liberation/dcs_liberation#2051] opened 2022-03-06 13:39 UTC
**Is your feature request related to a problem? Please describe.**
At the moment, it is unclear how the computer opponent prioritizes buying air and ground assets. It does not seem to adapt to player investments, and overprioritizes buying aircraft, leading to awkward force compositions of 113 aircraft, 2 tanks and one artillery piece.

This in turn leads to a campaign with minimal player agency, as airfields will be taken in quick succession, regardless of what players might do (CAP, CAS, Strike etc).

**Describe the solution you'd like**
Assumption: frontline compositions are already calculated based on the relative strength between both sides, and the rest are held in reserve.

Simple option: Make it possible for the player to force the computer to prioritize air or ground (maybe a slider or a drop-down with a few preset options like 20% air and 80% ground etc)

Complex option: make the computer cheat a bit and "see" what the player buys and counter that by investing more in a specific area (air/ground/anti air/anti tank/artillery etc)

**Comment by Starfire13** [comment] 2022-03-06 21:11
Duplicate of https://github.com/dcs-liberation/dcs_liberation/issues/505

**Closed as completed by Starfire13** 2022-03-06 21:11 UTC
Labels: enhancement
