### ISSUE TITLE
Unable to accept results, AssertionError in closest_opposing_control_points

### ISSUE THREAD

**Issue by ali4000** [dcs-liberation/dcs_liberation#1555] opened 2021-08-16 20:28 UTC
**Describe the bug**
A new variant of the "unable to accept result" bug when the campaign is won, somewhat similar to #677 and #833

**To Reproduce**
I played the last (winning) mission on Road to Dubai, and after taking the last airfield (Al Minhad) and destroying almost all remaining enemy units, I was unable to submit the results with:

2021-08-16 21:50:43,046 :: INFO :: Will run redeploy for Al Minhad AFB
2021-08-16 21:50:43,141 :: INFO :: finish_event: event not in the events!
2021-08-16 21:50:43,141 :: INFO :: Pass turn
2021-08-16 21:50:43,141 :: INFO :: Units halting at Al Dhafra AFB.
2021-08-16 21:50:43,142 :: INFO :: Skip Night mission due to user settings
2021-08-16 21:50:43,144 :: DEBUG :: Turn finalization took 0:00:00.002865
Traceback (most recent call last):
  File "windows\QWaitingForMissionResultWindow.py", line 211, in process_debriefing
  File "game\game.py", line 382, in pass_turn
  File "game\game.py", line 443, in initialize_turn
  File "game\game.py", line 403, in set_bullseye
  File "game\theater\conflicttheater.py", line 688, in closest_opposing_control_points
AssertionError

**Expected behavior**

Submitting the winning turn succeeds.

**Additional information**
Liberation savegame, console log, state.json and .miz attached:
[liberation_4.1.1_bug.zip](https://github.com/dcs-liberation/dcs_liberation/files/6995212/liberation_4.1.1_bug.zip)

**Version information (please complete the following information):**
 - DCS Liberation 4.1.1
 - DCS World Open Beta 2.7.5.10869

**Comment by DanAlbert** [comment] 2021-08-16 22:45
Duplicate of #978

**Closed as completed by DanAlbert** 2021-08-16 22:45 UTC
Labels: bug
