### ISSUE TITLE
Plane takeoff spawn starts in trees, explodes

### ISSUE THREAD

**Issue by LorenzoBoccaccia** [dcs-liberation/dcs_liberation#2030] opened 2022-02-25 15:55 UTC
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1897885878

### Description

![image](https://user-images.githubusercontent.com/3062853/155745030-fe913d5e-be4f-4e93-a617-3886661e80fa.png)

SEAD WARLUS taking off crashes into trees, being placed off from the runway

it doesn't show up as taxing/startingin the liberation window

mission crop:

![image](https://user-images.githubusercontent.com/3062853/155746075-b0eef88c-e76b-410f-8323-404a3abbe5a5.png)

campaign save + nextturn mission in attachment.

### Save game and other files

[1.zip](https://github.com/dcs-liberation/dcs_liberation/files/8142452/1.zip)

**Comment by walterroach** [comment] 2022-03-04 16:55
I ran the attached miz as well as one generated by the save file several times and the group you show exploding in Tacview successfully climbs away from the airport.  If you re-run the .miz do you get the same result?  My bet is my inability to reproduce is due to the DCS AI doing something differently on your run of the .miz.

The flight is intentionally not set to takeoff from the airport, as it's an in progress flight.

**Comment by LorenzoBoccaccia** [comment] 2022-03-04 20:35
so I've tried and I can reproduce it, are you all on openbeta by any chance? I'm on stable.

![image](https://user-images.githubusercontent.com/3062853/156837757-f9d960a9-e9cd-4003-b94d-dc8f1dc1bdff.png)


e: I've tried switching but apparently there aren't changes. can it be I've not the f16 module, so it's using a different flight model? idk

**Comment by DanAlbert** [comment] 2022-03-04 20:40
I doubt it's related, but FWIW Liberation doesn't support DCS stable. It's not possible for the game to support more than one release of DCS at a time.

**Comment by walterroach** [comment] 2022-03-04 20:53
My testing was done on open beta, 2.7.10.19473

We might explore setting a floor (or increasing the floor if we have one) for low altitude limits on in progress flights.  30m is pretty spicy for the AI

**Comment by DanAlbert** [comment] 2022-03-04 22:57
There is already a substantial floor: https://github.com/dcs-liberation/dcs_liberation/blob/980d8f3092be8d6a18f10f601238385160c3ebc0/game/missiongenerator/aircraft/flightgroupspawner.py#L34

**Comment by walterroach** [comment] 2022-03-04 23:38
Something didn't work right on this flight then, will look into it further.

**Comment by DanAlbert** [comment] 2022-03-05 00:45
I think when I added that floor I didn't actually have a save that I could use to verify, so it might just not work.

**Comment by DanAlbert** [comment] 2022-10-10 05:42
This happens for any flight that is immediately engaged upon takeoff. That floor is only applied to MSL altitudes (because why would you have an AGL altitude where this is a problem?), and the combat flight state uses the previous state's altitude as the spawn altitude. The previous state was navigation from takeoff to hold, and 0 seconds into that journey, so it was at 0 AGL.

There's a bit of a wtf here as well: https://github.com/dcs-liberation/dcs_liberation/blob/207d56c2e97e19f294de978a05639ce28ebd5a80/game/ato/flightstate/navigating.py#L42-L52

This obviously has fairly nonsense behavior whenever one of the waypoints is AGL and the other is MSL, since we're lerping between two values with different units. There isn't really a great solution to this, since we can't know the MSL altitude of any AGL waypoint.

I'm going to try to get a save game that repros on a modern build so I can work on a patch. I can guess at a fix, but the code around here has changed a lot since the build this was reported against.

**Comment by DanAlbert** [comment] 2022-10-10 05:52
#2212 was a dup of this. No one spotted the dup, but #2212 was fixed by https://github.com/dcs-liberation/dcs_liberation/pull/2302, so this is also already fixed.

**Closed as completed by DanAlbert** 2022-10-10 05:52 UTC
Labels: bug
