### ISSUE TITLE
How to import end mission results

### ISSUE THREAD

**Issue by HubFly35** [dcs-liberation/dcs_liberation#3093] opened 2023-07-20 17:48 UTC
### Affected versions

8.1.0

### Build information

I'm trying to figure out how to import into the wizard/liberation my end mission resluts. What format that is?....where to grab it in DCS and where to import it to?...etc. At the end I see the manually submit (advanced users), but i don't know what format to imput and/or where to grab that needed file in DCS. 

### Campaign name

any/all

### Blue faction

any/all

### Red faction

any/all

### Description

I'm trying to figure out how to import into the wizard/liberation my end mission resluts. What format that is?....where to grab it in DCS and where to import it to?...etc. At the end I see the manually submit (advanced users), but i don't know what format to imput and/or where to grab that needed file in DCS. 

### Log file

any/all

**Comment by Starfire13** [comment] 2023-07-20 22:04
That information is in the wiki. If you are new to Liberation, I strongly recommend reading through it. https://github.com/dcs-liberation/dcs_liberation/wiki/Dedicated-Server-Guide#getting-the-result-of-the-mission

This is not a bug report by the way (since you're not reporting a bug), so I am closing it.

**Closed as not planned by Starfire13** 2023-07-20 22:04 UTC
Labels: bug
