### ISSUE TITLE
"Accept results" button not doing anything when finishing a mission.

### ISSUE THREAD

**Issue by ttenor12** [dcs-liberation/dcs_liberation#1479] opened 2021-08-01 05:31 UTC
This has happened twice already and the first time I had to restart the campaign when I was already pretty advanced. Today I finished a mission and when I clicked "Accept Results", nothing happened. Asked in the Liberation discord and they asked me to file a bug with the Stage.json file and my liberation save.
[Campaign bug.zip](https://github.com/dcs-liberation/dcs_liberation/files/6912168/Campaign.bug.zip)

**Comment by bgreman** [comment] 2021-08-02 17:05
@ttenor12 Do you happen to have the generated .miz file?  When I ran this, I was able to successfully import the state.json, it looks like this may have been a campaign issue that was subsequently fixed in the upcoming 4.1 release, or one of the several convoy-related issues that was corrected.

**Comment by ttenor12** [comment] 2021-08-02 22:01
Sure, here it is. After that error happened, I didn't save progress because when it happened the first time in my first campaign, it basically made it unplayable. Hope it helps.
[liberation_nextturn.zip](https://github.com/dcs-liberation/dcs_liberation/files/6919859/liberation_nextturn.zip)

**Comment by RndName** [comment] 2021-08-08 11:43
I was able to reproduce the issue and can say it was already fixed with my PR #1455

The issue was that an CP Capture prevented an already planned transfer from being completed and there ran into an issue.

**Closed as completed by RndName** 2021-08-08 11:43 UTC
Labels: bug

**Comment by RndName** [comment] 2021-08-08 11:56
@ttenor12 if you want to proceed with your current campaign you can also use the current preview build for V4.1 which has this fix for the issue and will allow you to proceed the campaign. https://github.com/dcs-liberation/dcs_liberation/wiki/Preview-builds will advise you on how to download one of the preview builds from here:
https://github.com/dcs-liberation/dcs_liberation/actions/workflows/build.yml?query=branch%3Adevelop-4.x+event%3Apush

**Comment by ttenor12** [comment] 2021-08-09 01:12
Thank you so much! Will continue my campaign then.
