### ISSUE TITLE
Better simulation Balancing

### ISSUE THREAD

**Issue by KeeseAF** [dcs-liberation/dcs_liberation#1410] opened 2021-07-05 01:40 UTC
As discussed in the Feature-Request discord, im just looking for small tweaks in AI frontline progression. Im using the Persistent squadrons as one pilot and if im not scheduled to fly that turn, then I leave it up to the lads and gents for that turn to continue the campaign. However no matter how bad ass pilots and ground forces are while actually flying within dcs, when you skip the turn the planes don't takeoff or do their mission, and you're ground forces are as soft as paper. All im asking for is just small simulation within the Liberation UI so that My side doesn't get punished because my scheduling officer didn't schedule me to fly that turn.
So basically.
1. Tweak the simulation within OP LIB UI, so that its not a constant losing war whenever i decide to take a turn off/or im not scheduled
2. Planes and Ground forces are able to *simulate* victories and defeats IE, progression on frontlines, capturing bases, destroying key targets, and logistical movements like transferring pilots and planes
3. Tweaks in the benefits so that leveling AI don't get level up as quickly without actually flying within DCS.

Im not looking for a Total War Simulation within the UI as there are better games that does it. Im just looking for a tweak in an already amazing software to help enhance this mod even greater than what it already is.

Thanks

**Comment by DanAlbert** [comment] 2021-07-06 20:32
Duplicate of #953

**Closed as completed by DanAlbert** 2021-07-06 20:32 UTC
Labels: enhancement
