### ISSUE TITLE
Skynet error without skynet being enabled 

### ISSUE THREAD

**Issue by JeffreyCor** [dcs-liberation/dcs_liberation#2292] opened 2022-07-02 16:45 UTC
### Affected versions

Development build

### Development build

6.0.0-4042

### Description

After having been able to play though a few missions am no longer able to start a mission due to an error stating "Group has no skynet usable unit". I do not have Skynet turned on in the plugin options nor was it turned on since starting the campaign. Issue remains if skynet is enabled and also if flights are removed. Error is coming up when Takeoff is pressed. Passing turn to skip ahead does not workaround the problem.

### Save game and other files

[Vietnam6.zip](https://github.com/dcs-liberation/dcs_liberation/files/9033329/Vietnam6.zip)
![skynet error](https://user-images.githubusercontent.com/7409930/177009104-684a681e-1362-4b03-baa4-402a70ecfde5.jpg)
[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/9033331/liberation.log)

**Comment by Raffson** [comment] 2022-07-02 16:53
Interesting, I've been working on IADS lately and afaik this exception should not be possible to occur, but apparently it can so now I'm really curious 🧐

**Comment by JeffreyCor** [comment] 2022-07-02 18:01
Figured I'd find the impossible, just my luck. :P

**Comment by Raffson** [comment] 2022-07-02 18:46
I'll be settling behind my desk soon, hoping I'll be able to crush this bug in no time 🤞

**Comment by Raffson** [comment] 2022-07-02 19:56
https://github.com/dcs-liberation/dcs_liberation/blob/cc4237d0762cea396fe56134adf2bc64fa1682c4/game/theater/iadsnetwork/iadsnetwork.py#L38-L58

Printing some extra debug info in the exception seems to point to an EWR (TROUT) that's dead. So I think line 41 is the culprit, because what follows in the 'if' statement assumes there's a static object if it's dead. However an EWR unit is still a vehicle group and if "generate carcasses for units destroyed in previous turns" is turned off, I can see how this becomes a problem. The thing that confuses me though is the fact that I have similar situations (i.e. dead EWR units) in other campaign files and it doesn't seem to be a problem, so there's got to be something else that goes wrong.

**Comment by Raffson** [comment] 2022-07-02 20:27
Ok I think I figured it out but I'll have to do a little test to check if my reasoning is correct. Afaik IADS network doesn't update during processing of mission results, so if that EWR unit got taken out last turn, that might explain the problem. My PRs for IADS should fix this if my test is successful.

Edit: however I don't think it's gonna fix your save-file because essentially it's in an invalid state, but I might have a way to fix that for you so fingers crossed 🤞 😂

**Comment by Raffson** [comment] 2022-07-02 21:05
Ok so my test was successful, I managed to recreate the problem in a different save-file so it's definitely linked to the processing of the mission results. PR #2287 should solve the problem, but it depends on #2286 and #2285. As for your save-file, I'll try filtering your iads network so it's back in a valid state, but you should know that until those PRs are merged your save-file can still get messed up if you destroy EWR units.

**Comment by Raffson** [comment] 2022-07-02 21:19
Also @DanAlbert, while my PRs ought to solve this particular exception, there's the fact that skynet is disabled, so it shouldn't be generating iads at all right? I would think `luagenerator.py` should check if the setting is enabled before generating the plugin data for iads, but I'm not sure if that would have a different unintended side-effect.

**Comment by DanAlbert** [comment] 2022-07-02 21:43
/shrug I don't know how this works. @RndName

**Comment by Raffson** [comment] 2022-07-02 21:44
[Vietnam6-fix.zip](https://github.com/dcs-liberation/dcs_liberation/files/9033753/Vietnam6-fix.zip)

@JeffreyCor Meanwhile your save-file is fixed 😉

**Comment by JeffreyCor** [comment] 2022-07-02 22:57
> [Vietnam6-fix.zip](https://github.com/dcs-liberation/dcs_liberation/files/9033753/Vietnam6-fix.zip)
> 
> @JeffreyCor Meanwhile your save-file is fixed 😉

Far more than a ever hoped :) 
Thank you very much! :)

**Comment by RndName** [comment] 2022-07-03 08:30
> Also @DanAlbert, while my PRs ought to solve this particular exception, there's the fact that skynet is disabled, so it shouldn't be generating iads at all right? I would think `luagenerator.py` should check if the setting is enabled before generating the plugin data for iads, but I'm not sure if that would have a different unintended side-effect.

@Raffson @DanAlbert These are two things here. 
1) The issue described in this bug report never occured during my testing. Is this EWR some kind of Map object? Because to allow map objects to be handled by skynet there is a workaround of placing a static unit right at the point of that map object. But this should be handled correctly as far as i remember when i introduced this functionality. So the other possibility is that with the latest changes on the iadsnetwork class something went wrong (i can not really debug it nor do i have a feeling about that specific build number). But i would assume that it is somehow connected with the latest changes.
2) Generating the IADS lua data when skynet is disabled. You're right in the current implementation this IADS data is only used from the skynet plugin so we could disable generating this data. But the initial idea was that this lua data can be used by other plugins as well (like the ATC thing or some server hosting tools or whatever). As far as i know nobody is using this info so we can disable it. I do not see any benefits of -not- adding this data to the lua data table besides some few cpu cycles we can avoid. Totally up to you how you want to proceed with it. I dont have a strong opinion i just went the approach of offering the data so that creative people can start using it :)

**Comment by Raffson** [comment] 2022-07-03 10:56
@RndName EWR is a vehicle group afaict (hence my doubt about line 41), and the exception only occurs if you've destroyed an EWR unit in the previous turn. The reason is simply because the EWR unit isn't removed from the network when the mission results get processed, which I assume isn't intentional. As for generating IADS data even when skynet is disabled, your explantation makes sense so I guess we don't need to touch the luagenerator.

But going back to line 41 in iadsnetwork.py, it's still unclear to my why an EWR unit (whether it be ground based or naval) is handled like an IADS buildings. To me it seems to make more sense if it's handled like SAMs, SAMasEWRs and PDs, or am I missing something?

**Comment by RndName** [comment] 2022-07-03 11:24
> But going back to line 41 in iadsnetwork.py, it's still unclear to my why an EWR unit (whether it be ground based or naval) is handled like an IADS buildings. To me it seems to make more sense if it's handled like SAMs, SAMasEWRs and PDs, or am I missing something?

Read the comments about that. Group name is not equal unit name. This is a requirement on how skynet works on the lua side

**Comment by RndName** [comment] 2022-07-03 11:26
I would recommend debug the call stack back to the caller of this dcs name function to figure out why they request the name of the unit. Having dead tgos in the network is correct. But they do not participate anymore. Dead vehicles will not spawn. Dead statics will spawn but will be marked as dead.

**Comment by Raffson** [comment] 2022-07-03 11:43
> I would recommend debug the call stack back to the caller of this dcs name function to figure out why they request the name of the unit. Having dead tgos in the network is correct. But they do not participate anymore. Dead vehicles will not spawn. Dead statics will spawn but will be marked as dead.

Looking at the traceback it's coming from the luagenerator upon calling skynet_nodes. And yeah, dead units should fall in the "not participating" case, though in order for that to happen, "update_tgo" (in iadsnetwork.py) needs to be called when an IADS unit dies which doesn't happen in the current build. This problem should be fixed in #2287, but still I'm confused with the static dead units for EWR. Like, how would that work for a naval unit that got sunk?

**Comment by RndName** [comment] 2022-07-03 12:32
I see. Well in the previous version it was expected that dcs_name_for_group could raise an IadsNetworkException during the skynet_nodes routine. This was removed with https://github.com/dcs-liberation/dcs_liberation/commit/8c2c3530712ad196ba9121e6492a3ef1ec8df65b and is now unhandled. Therefore this issue here is expected.

This exception basicly tells you "hey you want to add a dead group to skynet" this will not work and will produce a scripting error whenever the mission will be running. Therefore these dead units were not added before.

But having TGOs with only dead units inside the IADS Network is expected behaviour (destroyed EWR is the best example here) because you could repair this EWR and it will participate again (currently only possible for blue).

**Comment by Raffson** [comment] 2022-07-03 13:11
> But having TGOs with only dead units inside the IADS Network is expected behaviour (destroyed EWR is the best example here) because you could repair this EWR and it will participate again (currently only possible for blue).

Buying a new EWR unit would trigger an IADS update via line 261:
https://github.com/dcs-liberation/dcs_liberation/blob/cc4237d0762cea396fe56134adf2bc64fa1682c4/qt_ui/windows/groundobject/QGroundObjectMenu.py#L258-L271

Effectively adding the unit back to the network so that's not a problem. But looking at the "update_tgo" method in iadsnetwork.py, a dead unit being updated (should happen during processing of mission results but doesn't, that's what #2287 is for) would be removed first, and then excluded because "node_for_tgo" will return None. If that happens, the exception won't occur. So all I can conclude is that everything will be correct as it is as soon as parts 2, 3 & 4 are merged for IADS. To be clear, this is independent from #2281.

**Comment by RndName** [comment] 2022-07-03 15:55
@Raffson That should be a discussion made in #2281 or one of the other PRs (which i have not looked at) but not in this Issue over here. To solve this issue over here we have 2 possible solutions. Either merge all your PRs (which i can not review atm) or implement a hot fix which adds a handling for Nodes without alive units (example: let dcs_name_for_group return None and handle it on caller side).
But to be clear this issue is a game breaker for everyone with the latest build as long as there is a fix available. I personally would prefer the short term hot fix as long as the other PRs are not reviewed but we can also go with your PRs. @DanAlbert can you review the open PRs of Raffson? Currently the whole update process is not working correctly so i am fine with reworking the whole logic as you propose with your PRs ;)

**Comment by Raffson** [comment] 2022-07-03 16:02
I'll start on the hot-fix just in case because clearly I missed that I'm depending on the update when an iads unit is killed during the refactor of exceptions, and it is a game breaker indeed, for which I do apologize...

**Comment by RndName** [comment] 2022-07-03 16:15
> I'll start on the hot-fix just in case because clearly I missed that I'm depending on the update when an iads unit is killed during the refactor of exceptions, and it is a game breaker indeed, for which I do apologize...

Thanks! i think it is the fastest way to deal with it until your PRs are merged. They will change the whole update process so that it is finally working and will ultimately also make this hotfix obsolete but until then the game will not break :D The good thing is that currently nearly no campaign supports the advanced IADS so the missing update routine will not hit as hard as this issue.
Thanks for looking into it @Raffson

**Comment by Raffson** [comment] 2022-07-03 16:47
No problem, my pleasure ;)

**Closed as completed** 2022-07-04 14:02 UTC
Labels: bug
