### ISSUE TITLE
Ability to select a livery for the squadrons at campaign start.

### ISSUE THREAD

**Issue by linmar22** [dcs-liberation/dcs_liberation#2054] opened 2022-03-07 01:03 UTC
It would be nice if we could select a livery for a given squadron when setting up the campaign.

**Is your feature request related to a problem? Please describe.**
Started up a Ukraine playthrough, and noticed some of the planes (Mig-29s for example) use the default livery, which happens to be Russian... red star, "VVS Rosiyi" on the side and everything.

**Describe the solution you'd like**
I imagine a simple dropdown to that is populated with the available liveries from the base game and Saved Games/DCS.openbeta wouldn't be too hard to do.

**Additional context**
This would also add to the immersion, as players could set up different liveries, adding some "life" to the airbase scene by making it look like more than one squadron is stationed there.

**Comment by Starfire13** [comment] 2022-03-07 02:37
Duplicate of https://github.com/dcs-liberation/dcs_liberation/issues/1861

**Closed as completed by Starfire13** 2022-03-07 02:37 UTC
Labels: enhancement
