### ISSUE TITLE
Map Object Strike Results Not Counted

### ISSUE THREAD

**Issue by hisothiro** [dcs-liberation/dcs_liberation#2969] opened 2023-06-05 14:05 UTC
### Affected versions

7.1.0

### Build information

DCS Liberation 7.1.0

### Description

When destroying buildings as part of a map object strikes, the results aren't counted, and the buildings are still marked as undamaged on the UI after the mission.

This happened to me using the Up the Coast campaign on Caucasus but Toad VCAW-1 on the Discord reported it also happened on a campaign in PG. 

### Save game and other files

This works with any saved game with map object strikes. It's easy to reproduce using the Up the Coast campaign. 
I deleted my save before writing this bug but I was on turn 1 so it would not have helped much.

**Comment by DanAlbert** [comment] 2023-06-05 17:53
> I deleted my save before writing this bug but I was on turn 1 so it would not have helped much.

You'd be surprised. Pretty much any time there isn't a save attached the bug turns out to be reproducible. I'll wait.

**Comment by DanAlbert** [comment] 2023-06-05 17:54
You deleted it and cleared the recycle bin?

**Comment by hisothiro** [comment] 2023-06-05 18:01
> You deleted it and cleared the recycle bin?

Yes, unfortunately. I'll find some time to reproduce it and I'll attach my save file. It should be pretty quick.

**Comment by hisothiro** [comment] 2023-06-05 20:53
[bug_test.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11657614/bug_test.liberation.zip)
 @DanAlbert Here's a save file where I recreated the issue.

**Comment by DanAlbert** [comment] 2023-06-05 23:43
Thanks! I don't suppose you know if this started happening because of a liberation update or a DCS update?

**Comment by hisothiro** [comment] 2023-06-06 02:04
Sorry, I took a bit of a DCS hiatus and came back to try Liberation 7 so I couldn't say.

**Comment by DanAlbert** [comment] 2023-06-06 02:08
No worries, just thought I'd check.

**Comment by Starfire13** [comment] 2023-06-18 01:46
I can confirm this has been fixed in dev build. Should this get put back in 8.0?

**Comment by DanAlbert** [comment] 2023-06-18 06:58
Yeah, it's in the changeling, but we'd forgotten to fix GitHub :)

**Closed as completed by DanAlbert** 2023-06-18 06:58 UTC
Labels: bug
