### ISSUE TITLE
Error when trying to Edit a flight of F/A-18Cs after it has been created

### ISSUE THREAD

**Issue by Jay7540** [dcs-liberation/dcs_liberation#2455] opened 2022-09-27 02:41 UTC
### Affected versions

5.2.0

### Description

When I try to edit a Flight for F/A-18Cs after the flight has already been created, I get an error BRU_42A_ADM_141A, and it lists a bunch of Files in the error message (which I attached below). This has only happened on the Hornets so far.

### Save game and other files

![Screenshot 2022-09-26 224002](https://user-images.githubusercontent.com/34962760/192418912-060f384b-0bc5-49db-b979-ac00f6a76716.png)

**Comment by DanAlbert** [comment] 2022-09-27 03:59
Duplicate of #2320

**Closed as not planned by DanAlbert** 2022-09-27 03:59 UTC
Labels: bug
