### ISSUE TITLE
DEAD Target getting culled

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#926] opened 2021-02-27 21:40 UTC
**Describe the bug**
I generated a DEAD mission in "Nevada - Exercise Vegas Nerve" and the target was culled.

**To Reproduce**
1)  Generate "Nevada - Exercise Vegas Nerve" campaign.
     - USA 2005, Russia 1990, 
     - No carriers/LHA
     - Start date: Mid-90s Summer [1995]
     - Culling of distant units enabled (100 km) + No cull around aircraft carriers
     - Restrict Weapons by date
     - Skynet, Jtac Autolase
2)  Generate a Player DEAD mission far from the front line.
3)  Observe that a no culling region is not generated around target.

**Expected behavior**
Generate a no culling zone around each mission's target.

Alternatives if this is on purpose:
- Warn the user that there are packages whose target's are outside the no culling zone
- Make a no culling zone around the player's targets, cull AI packages when their target's outside a no culling zone.

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

[Nevada_Red_Flag_Culling.zip](https://github.com/Khopa/dcs_liberation/files/6055477/Nevada_Red_Flag_Culling.zip)

**Version information (please complete the following information):**
 - DCS Liberation 2.4.2

**Additional context**
![Campaign_Culling](https://user-images.githubusercontent.com/74509817/109400981-29547700-7909-11eb-9feb-07856e80bd7e.png)

![F10_In_Mission](https://user-images.githubusercontent.com/74509817/109400983-2ce7fe00-7909-11eb-8b10-6a0202215fd4.png)

**Comment by DanAlbert** [comment] 2021-03-13 21:00
I can't load your save game in either 2.4 or 2.5:

```
2021-03-13 12:58:34,506 :: ERROR :: Invalid Save game
Traceback (most recent call last):
  File "C:\Users\dan\src\dcs_liberation\game\persistency.py", line 38, in load_game
    save = pickle.load(f)
  File "C:\Users\dan\src\dcs_liberation\venv\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
```

**Comment by SnappyComebacks** [comment] 2021-03-13 21:19
> 
> I can't load your save game in either 2.4 or 2.5:
>

Strange, I just downloaded the files that were attached and was able to open it in 2.4.2 and 2.4.3.

**Comment by DanAlbert** [comment] 2021-03-13 21:53
The error in 2.5:

```
Traceback (most recent call last):
  File "C:\Users\dan\src\dcs_liberation\game\persistency.py", line 38, in load_game
    save = pickle.load(f)
_pickle.UnpicklingError: invalid load key, 'n'.
```

I have no idea what would be causing that. Googling seems to just turn up the answer of "something's wrong, good luck".

**Comment by MrMagicMan** [comment] 2021-03-21 07:54
Different location map etc.. but still a dead strike. Here is my save game with the same issue with culling, and from a privious turn without it. (Posted here based on "Missing culling exclusion zone #946")

From Liberation 3.4.2
Jaguar Site was culled.
![image](https://user-images.githubusercontent.com/10494948/111897857-bb2b3d80-89f8-11eb-90ce-26737bc41c6f.png)
[CullingIssue Turn 6.zip](https://github.com/Khopa/dcs_liberation/files/6177022/CullingIssue.Turn.6.zip)

Interestingly, this was the second strike on that same site, and the first time it was there in the map.
Here is the information from the first run at it where it was there.


![image](https://user-images.githubusercontent.com/10494948/111897883-e877eb80-89f8-11eb-972a-b46143421d51.png)
[CullingIssue Turn 5 Everything OK.zip](https://github.com/Khopa/dcs_liberation/files/6177026/CullingIssue.Turn.5.Everything.OK.zip)

Both had aircraft from Gudauta, the only thing I can note was that the join up was further away in the second strike, and there were multiple airfields but the multiple airfield was not consistent when this happened to me as noted in #946.

**Comment by DanAlbert** [comment] 2021-04-10 23:04
Not culled when I generate it: ![image](https://user-images.githubusercontent.com/315852/114286676-c2e96b00-9a15-11eb-8634-29380f1e5de8.png)

That's from the turn 6 one, with culling enabled.

In the log I see

```
2021-04-10 15:56:54,840 :: WARNING :: Found empty group in AA Defense Site
2021-04-10 15:56:54,840 :: WARNING :: Found empty group in AA Defense Site
2021-04-10 15:56:54,840 :: WARNING :: Found empty group in AA Defense Site
2021-04-10 15:56:54,840 :: WARNING :: Found empty group in AA Defense Site
2021-04-10 15:56:54,840 :: WARNING :: Found empty group in AA Defense Site
2021-04-10 15:56:54,841 :: WARNING :: Found empty group in AA Defense Site
```

But I think that's innocuous. Pretty sure that's warning about base AA sites that have been destroyed, so it's normal that they aren't being generated.

Closing as not reproducible on the assumption that the bug has since been fixed. If we get a save that lets us observe the behavior we'll reopen of course, but we can't do anything with the data we have :(

**Closed as completed by DanAlbert** 2021-04-10 23:04 UTC
Labels: bug, not reproducible
