### ISSUE TITLE
AI Aircraft spawn on inappropriate parking spots - leading to their destruction

### ISSUE THREAD

**Issue by Meyomyx** [dcs-liberation/dcs_liberation#1078] opened 2021-05-14 05:11 UTC
Before filing, please search the issue tracker to see if the issue has already been reported.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

- DCS Liberation save file (the `.liberation` file you save from the DCS Liberation window). By default these are located in your DCS saved games directory (`%USERPROFILE%/Saved Games/DCS`).
- The generated mission file (the `.miz` file that you load in DCS to play the turn). By default these are located in your missions directory (`%USERPROFILE%/Saved Games/DCS/Missions`).
- A tacview track file, especially when demonstrating an issue with AI behavior. By default these are located in your Tacview tracks directory (`%USERPROFILE%/Documents/Tacview`).
- The state.json file from the finished mission when the problem is related to results processing. By default these are located in your Liberation install directory.

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.3.1]:

**Additional context**

**Comment by Meyomyx** [comment] 2021-05-14 05:18
This mission spawned A10C II aircraft on helipads at Kalkhallah. Upon mission start, they all tried to taxi to the active runway and destroyed themselves. (Possibly a DCS issue related to this airfield??)

![Untitled](https://user-images.githubusercontent.com/70166005/118224559-5251c600-b47b-11eb-9cc6-73927f237b20.jpg)

**Comment by DanAlbert** [comment] 2021-06-05 02:34
Duplicate of #371

**Closed as completed by DanAlbert** 2021-06-05 02:34 UTC
Labels: bug
