### ISSUE TITLE
bf109 K4 in Germany 1940/1942 factions

### ISSUE THREAD

**Issue by DillieKoe** [dcs-liberation/dcs_liberation#2064] opened 2022-03-10 12:57 UTC
### Affected versions

Development build

### Description

according to wikipedia the bf109 K4 variant wasn't produced untill 1944 but the Germany 1940 and 1942 factions have it.

### Save game and other files

Check factions

**Comment by Starfire13** [comment] 2022-03-10 13:19
Duplicate of https://github.com/dcs-liberation/dcs_liberation/issues/1828

**Closed as completed by Starfire13** 2022-03-10 13:19 UTC
Labels: bug
