### ISSUE TITLE
Webapp or remote client access

### ISSUE THREAD

**Issue by WirtsLegs** [dcs-liberation/dcs_liberation#3444] opened 2024-10-02 15:40 UTC
Before filing, please search the issue tracker to see if this feature has already been requested.

If requesting a DCS AI feature, check If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Is your feature request related to a problem? Please describe.**
This is not related directly to a problem but would increase usability in the context where groups are using this on dedicated servers

**Describe the solution you'd like**
I would love to see an option for the UI to be exposed as a web server, or allow it to be connected to by a local client, some way of remote administration to simplify using it with a dedicated server when you want people to be able to use it that you dont necessarily want to give RDP access etc.

**Additional context**
Nothing else to add

**Comment by zhexu14** [comment] 2024-10-05 07:04
Suggestion makes sense but is a duplicate of #104 .

**Closed as completed by zhexu14** 2024-10-05 07:04 UTC
Labels: enhancement
