### ISSUE TITLE
CAS aircraft stray away

### ISSUE THREAD

**Issue by BigBoss329** [dcs-liberation/dcs_liberation#195] opened 2020-10-10 17:29 UTC
CAS aircraft almost never stick around the frontline to support ground troops. Instead, they go on suicide missions, deep behind enemy lines.
A-10s regularly go after S-300 positions and even go on ship hunts.

Would it be possible to limit CAS flights to strictly operate in the area near the frontline and RTB if they reach bingo, or run out of ordnance?

**Comment by celsodantas** [comment] 2020-10-13 15:48
Same on my mission. Here's what every single CAS mission is doing, including helicopters:

![image](https://user-images.githubusercontent.com/408219/95883943-829c7f00-0d49-11eb-8704-c06b2f4df443.png)

So they all die by the SAM sites that are very far from the frontlines.

I wonder if using MOOSE A2G Dispatcher would help here: https://flightcontrol-master.github.io/MOOSE_DOCS/Documentation/AI.AI_A2G_Dispatcher.html 

And the issue here is the DCS AI making bad life decisions. As the CAS waypoints are correcty placed on the map.

As you can see from this Mission Editor shot:

![image](https://user-images.githubusercontent.com/408219/95896298-0cecdf00-0d5a-11eb-9106-05e5b64e3383.png)

![image](https://user-images.githubusercontent.com/408219/95896502-53423e00-0d5a-11eb-8ce2-c093594971bc.png)

I also just noticed that the A-10CII plane saying on the radio "Ford1, defending SAM at bulls 309 for 60".

**Comment by celsodantas** [comment] 2020-10-13 18:23
Did some investigation and from my understanding the issue is on this line:

https://github.com/Khopa/dcs_liberation/blob/41445c3092185bc08dcbe8fd87bed790fee6ac39/gen/aircraft.py#L909

Where it's assigning the CAS unit to engage based on priority:

```
OpenFireWeaponFree = 1
"""AI will engage any enemy group it detects, but will prioritize targets specified in the groups tasking."""
OpenFire = 2
"""AI will engage only targets specified in its taskings."""
````
source: https://github.com/pydcs/dcs/blob/98a74ed2a90342160ec7763bf60f37b907b2856f/dcs/task.py#L1390-L1393

While the CAS units are not assigned to engage in SAM, it looks like they are engaging. In my mission, I have some SA10 that are painting the units around the battle field but are too far to fire at BLUEFOR. 

I was able to make the unit NOT fly north-west, towards the SAMs, by changing the ROE from `PRIORITY DESIGNATED` to `ONLY DESIGNATED` from the mission editor.

Here's an overview of the mission:

![image](https://user-images.githubusercontent.com/408219/95899951-47a54600-0d5f-11eb-96c7-a0f5fe6634c5.png)

__

I believe that changing that line to `OpenFire` will fix this, but might make the AI dumber.

**Comment by celsodantas** [comment] 2020-10-13 18:35
Further confirmed by having 1 group of helos with ROE `ONLY DESIGNATED` and the other I left with `PRIORITY DESIGNATED`

![image](https://user-images.githubusercontent.com/408219/95901351-35c4a280-0d61-11eb-9309-5a021a6d2db9.png)

I'm unsure if the `ONLY DESIGNATED` will make the unit useless. Unless we mark specific targets to be shot at. I noticed the helos now just cruising around after the change. But it was a bit inconclusive, as at some point I saw some A-10CII (marked with `ONLY DESIGNATED` engaging with some ground units.

I'm now wondering if the fix here is to only have SEAD missions to then proceed with the CAS attacks. Suppress the S10 first to only then move with the CAS. That would make pushing the frontline super hard, tho. As only ground unit would be engaging in fight on the first few rounds.

**Closed as completed** 2020-11-14 21:31 UTC
