### ISSUE TITLE
Manually change waypoint altitude

### ISSUE THREAD

**Issue by Freddofresh** [dcs-liberation/dcs_liberation#2640] opened 2022-12-16 12:09 UTC
Is it possible to have the option in Liberation to manually change each waypoint altitude for flights? This would be useful if you for example are doing a strike package with AI against a SAM site that has a ceiling for engagement like the SA-15 wich is hard to strike against with SEAD/DEAD since they are capable of shooting down incoming missiles. It would also help with fuel preservation for the AI with longer flight. 

Also with the helicopter Air assault missions, they tend to hug the ground wich makes the ingress time very very slow and they also tend to crash into things or terrain.

**Comment by Starfire13** [comment] 2022-12-16 13:08
Duplicate of https://github.com/dcs-liberation/dcs_liberation/issues/270

**Comment by Metal-121** [comment] 2023-01-14 18:07
Would love to see this be avaiable. Some attack runs is just suicidal and it tideous to make changes in ME.

**Comment by DanAlbert** [comment] 2023-01-14 19:14
Duplicate of https://github.com/dcs-liberation/dcs_liberation/issues/270

**Closed as not planned by DanAlbert** 2023-01-14 19:14 UTC
Labels: enhancement
