### ISSUE TITLE
Multiple UI refresh problems in package planner window(s)

### ISSUE THREAD

**Issue by ali4000** [dcs-liberation/dcs_liberation#3190] opened 2023-10-04 19:17 UTC
### Affected versions

Development build

### Build information

Present in 9.0.0-preview from git as of Oct 3.

### Description

The Waypoints window has some refresh problems:

- If you delete a waypoint it disappears as expected, but if you then continue to delete more, they aren't visually removed until you click somewhere in the waypoint table, or close and re-open the window. Also, while not exactly a refresh problem, the first waypoint of a flight cannot be deleted. Nothing happens if you try -- except for the curiosity that the scrollbar at the bottom of the waypoint table disappears and the box holding the table is expanded slightly to show the entire TOT/DEPART label.

- Adding waypoints suffer a similar problem but immediately; the new waypoint will not be shown until you re-open the window, even if you click around in the table

### Save game and other files (save game required, bugs without saves will be closed)

UI bug, no savegame required, but here's an example flight

[refresh_bugs.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/12807323/refresh_bugs.liberation.zip)

**Comment by DanAlbert** [comment] 2023-10-04 21:18
Could you file multiple bugs please? GitHub makes it hard for us to track more than one problem in a single report. It's fine if they're all the same save game if each problem is visible. The package window is almost certainly unrelated to the waypoints window.

**Comment by ali4000** [comment] 2023-10-05 10:50
Pilot status filed as separate bug #3192

**Comment by DanAlbert** [comment] 2023-10-05 22:22
Thanks! We'll hopefully get to both in 9 but now we at least won't lose track of them if we run out of time.

**Comment by DanAlbert** [comment] 2023-11-10 23:06
Anyone know if this is a regression or not? If it's a regression we should fix it before 9 releases, but if it isn't I'd rather not keep holding up 9 until I have the time to look, since I haven't for the past few weeks.

**Comment by zhexu14** [comment] 2023-11-10 23:55
I just checked and most of the issues raised here are fixed in the latest development build. 

The only thing that isn't "fixed" is the inability to delete the first waypoint, which is a feature rather than a bug, based on my reading of the discussions on #3191 .

**Comment by DanAlbert** [comment] 2023-11-11 03:03
Ah, even better. Thanks!

**Closed as completed by DanAlbert** 2023-11-11 03:03 UTC
Labels: bug, UX
