### ISSUE TITLE
Steam Requirement?

### ISSUE THREAD

**Issue by clairmont32** [dcs-liberation/dcs_liberation#3461] opened 2024-11-15 02:39 UTC
### Affected versions

11.1.1

### Build information

DCS Liberation 11.1.1

### Description

Unable to start a new mission due to steam requirement. Im unsure as to why this is as its not mentioned anywhere in the documentation that I've combed through.
![image](https://github.com/user-attachments/assets/2663e9a6-1610-4a36-a622-3f0be05fae4c)

### Save game and other files (save game required, bugs without saves will be closed)

[Brightstar 2024.liberation.zip](https://github.com/user-attachments/files/17760693/Brightstar.2024.liberation.zip)

**Comment by Starfire13** [comment] 2024-11-15 02:52
This is a problem caused by a corrupt entry for Steam in your system registry. Not a Liberation problem. There is no requirement for Steam.

**Comment by zhexu14** [comment] 2024-11-15 08:37
Liberation looks for your DCS install path in the following order:

1. By looking at the Windows Registry Key *Software\Eagle Dynamics\DCS World*
2. By looking at the Windows Registry Key *Software\\Eagle Dynamics\\DCS World OpenBeta*
3. By looking for a Steam Installation

I assume you're running off a standalone installation of DCS? If so, neither of the Windows Registry keys are present (maybe a DCS installation issue?) and so Liberation can't find your DCS install. You will need to populate those keys somehow (manually or by reinstalling DCS). I'll close this issue for now but please re-open it if these steps don't fix your issue.

**Closed as completed** 2024-11-15 08:38 UTC
Labels: bug
