### ISSUE TITLE
Dev build busted

### ISSUE THREAD

**Issue by mikef-phy** [dcs-liberation/dcs_liberation#2451] opened 2022-09-23 01:44 UTC
### Affected versions

Development build

### Development build

4211 

### Description

4211 is the last working dev build.

### Save game and other files

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/9630294/liberation.log)

no state file available

**Comment by DanAlbert** [comment] 2022-09-23 02:12
No, that campaign is busted :)

Duplicate of https://github.com/dcs-liberation/dcs_liberation/issues/2377

**Closed as not planned by DanAlbert** 2022-09-23 02:12 UTC
Labels: bug

**Comment by mikef-phy** [comment] 2022-10-13 13:09
ok.  cool.
________________________________
