### ISSUE TITLE
Red Untasked Aircraft Not Spawning for OCA Aircraft Mission

### ISSUE THREAD

**Issue by Stearmandriver** [dcs-liberation/dcs_liberation#1928] opened 2022-01-09 03:50 UTC
### Affected versions

5.0.0

### Description

Issue appears in 5.1 as well.  It appears that the only enemy aircraft that are being spawned are tasked aircraft.  Thus, OCA aircraft missions at a disabled airfield are impossible, as there are no targets.

### Save game and other files

[NoOCAAircraft.zip](https://github.com/dcs-liberation/dcs_liberation/files/7834430/NoOCAAircraft.zip)

**Comment by Starfire13** [comment] 2022-01-09 03:57
Looking at the air wing pane, those missing aircraft do not actually exist until the next turn, even though they show up in the control point info pane. Passing turn will have the aircraft re-appear on the next turn.

This issue appears to have been encountered multiple times by various folks who run Liberation via server (whether on a different machine or on the same one they play on) and have to manually submit their state.json.

**Comment by Starfire13** [comment] 2022-01-09 19:40
Potentially duplicate of #1880

**Comment by HILOK** [comment] 2022-02-20 17:51
hi, i had this happening today NOT running liberation on a server. all enemy aircraft were sitting on the ground, when i started the mission the first time (runway already destroyed). then i had to abort the mission and rework spawn times ( via TOT) due to mash-ups on the carrier. after that no more enemy aircraft on the field...

[state.zip](https://github.com/dcs-liberation/dcs_liberation/files/8104584/state.zip)

**Comment by DanAlbert** [comment] 2022-05-28 00:49
Aircraft spawning was rewritten entirely since 5.x. If there's a confirmed report of this happening with a recent build we can reopen, but a bug matching the description was definitely fixed as part of that rewrite, so I believe this is already fixed.

**Closed as completed by DanAlbert** 2022-05-28 00:49 UTC
Labels: bug
