### ISSUE TITLE
Choose which scripts to use on campaign starts

### ISSUE THREAD

**Issue by sith1144** [dcs-liberation/dcs_liberation#1772] opened 2021-11-20 12:34 UTC
I think it would be nice if one of the pages for campaign setup (the one where you select mods perhaps, or difficulty/money) asked what scripts you want to use. Currently you have to access the options menu to turn them on/off after going through the campaign start dialogue. They are essentially "hidden" features. Putting them in one of the dialogues makes them clearly available.

**Comment by Starfire13** [comment] 2021-11-20 14:19
What would be better is if such settings were stored in a config file in the Liberation folder in dcs.openbeta. I think most people just use the same settings each time, so it would be nice if the settings persisted instead of having to be set every single time.

I actually have a custom plugins folder that I copy and paste into each new Liberatoin install so I don't have to keep redoing my plugin setings eleventybillion times. However, stuf like performance settings and fast forward settings can't be preset that way.

**Comment by DanAlbert** [comment] 2021-11-20 20:30
Duplicate of #332

**Closed as completed by DanAlbert** 2021-11-20 20:30 UTC
Labels: enhancement
