### ISSUE TITLE
Uncheck the "group attack" setting for BAI missions.

### ISSUE THREAD

**Issue by Nosajthedevil** [dcs-liberation/dcs_liberation#1795] opened 2021-11-23 22:40 UTC
Liberation seems to currently check the "Group Attack" advanced setting in ME for BAI (and maybe all CAS) missions , causing all attacking units in the group to fire at the same targets if they launch at the same time. This wastes weapons and causes flights to be less effective than they could be if allowed to distribute targets.

Would it be possible to either have liberation create missions with Group Attack unchecked or add a switch to the UI to allow the player to select whether Group Attack is selected or not? 

I'm guessing there are situations, maybe like anti-ship, overloading a SAM site, or carpet bombing, where it's preferrable to keep this checked to launch as many weapons as possible at a single target. I can't think of a situation though where I would want to use more than one maverick per ground vehicle unless one's a miss.

**Comment by DanAlbert** [comment] 2021-11-26 21:15
Duplicate of #269

**Closed as completed by DanAlbert** 2021-11-26 21:15 UTC
Labels: enhancement
