### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by pierpaolobirdi** [dcs-liberation/dcs_liberation#2761] opened 2023-03-18 16:25 UTC
### Affected versions

6.1.1

### Build information

![image](https://user-images.githubusercontent.com/24416111/226118718-216a4aae-e25e-4d9b-8427-37b23404e90e.png)

### Description

I get this error when I click on take-off.
I send the previous liberation file, then the state file that generates the next shift, which is where the error appears.
[Liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11009012/Liberation.zip)

### Save game and other files

[Liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11009014/Liberation.zip)

**Comment by DanAlbert** [comment] 2023-03-18 18:53
> I send the previous liberation file, then the state file that generates the next shift, which is where the error appears.

Thank you! We've been getting these reports for ages but this is the first time we've had the _previous_ turn's save, which is the only way we can investigate.

**Comment by DanAlbert** [comment] 2023-03-18 19:17
Ugh. Because the transfer that's broken here is at an airlift-only location, the game was actually broken even in the previous turn.

We have this piece of data that keeps track of pending transfers, which maps a unit type to the quantity of units to be transferred. For some reason, that quantity waiting to be transferred sometimes is 0. It should never be zero; when the count goes to zero that entry should just be removed. We could of course detect that and suppress the error during generation, but we really want to know what's causing the data corruption in the first place, which is why we haven't done that.

That does give me some clues though. I'll see if I can spot anything suspicious, but I'm not really optimistic.

**Comment by DanAlbert** [comment] 2023-03-18 19:20
Hmm, wait. I think those airlift transfers I just mentioned are _a_ problem, but the crash here is clearly a convoy. It's probably broken in a few places, but the _convoy_ breakage should be debuggable...

**Comment by pierpaolobirdi** [comment] 2023-03-18 19:25
Thank you very much for your quick support.

I hope it will be of some use to you. I think the problem is in the ground convoy anyway. 
The air transfers were pending turns ago and did not create a problem.
If you need the previous states / turns I also have them saved... Just ask me for them.

If you find the solution and detect the incorrect state, please let me know so I can continue the campaign.

**Comment by DanAlbert** [comment] 2023-03-18 19:26
To get you moving again, it looks like the one causing the crash is a player-owned convoy moving from Ramat David to Damascus. The units for that convoy are 2 abrams and 0 paladins. You should be able to cancel that transfer to avoid the crash.

**Comment by pierpaolobirdi** [comment] 2023-03-18 19:28
I'm going to look and try to cancel it to see if that's what it is.... 

Anyway, I hope you will be able to detect these problems in time and prevent them from occurring in the future.

**Comment by pierpaolobirdi** [comment] 2023-03-18 19:39
A THOUSAND THANKS.

I have indeed reduced the number of units transferred from Ramar David to Damascus and it has been fixed

I hope as I said before that the reported files will help you to locate the error in order to correct it in future Updates.

Thank you very much for your effort, quick support and above all for this wonderful program.

**Comment by Raffson** [comment] 2023-03-18 19:47
Coincidentally I have investigated this yesterday, and decided to put the bandaid on. Started off by looking at the `split_transfer` method, and while there's definitely a bug where `take` can be 0, it's not the only issue. I managed to actually reproduce this thing on a consistent basis by transferring units by airlift to a FOB, and I think that last part is the significant one because when I look at the transfer dialog it shows an airlift going through an airbase and a convoy from that airbase to the FOB. Especially that second part makes it sound like the that convoy is being planned 1 turn too early, but that's as far as I got before calling it a night and simply putting a bandaid on it.

**Comment by DanAlbert** [comment] 2023-03-18 19:59
@pierpaolobirdi do you have any idea why ground units ended up at Golan South in the first place? There's no path for the front-line to get there, so there's no point defending it, and there's no factory there. Did you intentionally transfer units there, or did the game mistakenly route an airlift through there for some other transfer?

**Comment by pierpaolobirdi** [comment] 2023-03-18 20:04
These units moved because of our action.
The initial mission was modified and a FARP was created in South Golan (copied from the Golan Heights campaign to ease the path for helicopters). I don't think you have to worry about those units, I think we have always had them under control.
Anyway, if you need more clarifications or previous turns as well as the initial mission we created, you can send it to you for study.

**Comment by DanAlbert** [comment] 2023-03-18 20:11
> These units moved because of our action.

Could you elaborate? You mean you intentionally transferred units there, or you mean you purchased them, and they routed there automatically for some reason? The latter would be a second bug.

Those units are where the bug begins. When I load your save, I see this:

![image](https://user-images.githubusercontent.com/315852/226135780-a4130841-3f9e-4a7c-8b1f-c1c2e9a7546d.png)

The last transfer there (the airlift) is broken already in that save. The game data there is corrupted and includes a transfer order for 0 paladins. To fix the underlying bug rather than just mask it, I need to know how that happened. If you happen to have the save from turn 8 it might help.

**Comment by DanAlbert** [comment] 2023-03-18 20:15
On the assumption that this bug only appears as the result of a large airlift, I bet it's this: https://github.com/dcs-liberation/dcs_liberation/blob/bcb7d059c048f2263333c2e0e6aa8a5a8e181b12/game/transfers.py#L615

I'd love to prove that though. I think turn 8 would let me prove that easily, but I'll try to force a game into that situation in case you don't have it.

**Comment by pierpaolobirdi** [comment] 2023-03-18 20:20
[Liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11009501/Liberation.zip)
I attach the whole development of the game from the beginning together with the initial mission that was modified in the resources folder.

**Comment by pierpaolobirdi** [comment] 2023-03-18 20:22
I attach all the evolution of the game from the beginning together with the initial mission modified from the resources folder.

**Comment by DanAlbert** [comment] 2023-03-18 20:23
Excellent, thanks!

**Comment by DanAlbert** [comment] 2023-03-18 21:03
Using your campaign, I was able to craft a save that got into the same situation, which proved that at the very least my theory above was correct. https://github.com/dcs-liberation/dcs_liberation/pull/2762 fixes that bug. Gory details are in the commit message.

The reason this was so difficult to track down (this bug has been reported periodically since 3.0!) is that it's actually not possible in any of our included campaigns as far as I can tell. It can only happen when a very large airlift is ordered from a FOB that is not connected to the road network, _and_ that airlift has very specific counts of units (any unit type except the last one needs to be a multiple of the airlift capacity available), _and_ that airlift needs to deliver the units to somewhere other than their final destination so the units would finish their trip via road. The corruption happens _at least_ two turns before the crash (potentially more, depending on just how large the airlift was).

It's not really possible to prove that this was the cause of the failure in the save, because the save games don't tell me what orders you gave. Liberation should never create the circumstances that led to this behavior (units present at a disconnected FOB with no factory, where they cannot do anything useful whatsoever, transferring back to the road network by air). It looks like you did buy those units at that disconnected FOB on turn 0. I assume you manually transferred those out at some point, which would explain how this happened.

**Closed as completed** 2023-03-18 21:03 UTC
Labels: bug

**Comment by DanAlbert** [comment] 2023-03-18 21:07
This is fixed in 7 now. We have no plans for a 6.1.2. If we end up doing that we'll probably not cherry-pick this anyway, but rather suppress the error in 6 since the fix in 7 can't fix already-broken saves (suppressing the error is an option now that we've found the cause of the corruption, it won't hide the bug from us any more).

Anyone running into this bug in 6: if it's caused by one of _your_ transfers, just cancel all your pending transfers and replan them. It should not be possible for redfor to get itself into this situation. If you encounter that error and it's caused by a redfor transfer, please file a new bug.

**Comment by pierpaolobirdi** [comment] 2023-03-18 21:49
Perfect.
Thank you very much for your valuable and great work.
we hope that soon we will have 7
