### ISSUE TITLE
DCS Syria Map / A10 parking bug affecting Liberation mission starts

### ISSUE THREAD

**Issue by Meyomyx** [dcs-liberation/dcs_liberation#895] opened 2021-02-17 11:20 UTC
When creating an A10 strike flight from King Hussein, I could not get the flight to cold start ... despite it being set in the flight parameters. It consistently starts in the air. Upon re-opening Liberation, it has become an "air start" flight. Save it as "cold start" and it reverts to an air start flight.

After some investigation, it seems that the Syria map / A10 parking is bugged in that the A10 only has a few parking spots showing that can be used. Other aircraft do not seem to be affected and have the full number of spots available. Thus if the number of A10 aircraft exceed this small number of parking spots, the flight will be converted by the mission editor into an "air start" flight above that air base. The route isn't affected - including arrival back at the same airbase.

With "automatic aircraft purchase" in operation, Liberation has purchased more A10 aircraft than can start from the ground - which is the cause of my problem.

It looks like this is a bug with the Syria Map. At Al Dumayr, for example, there are 57 parking slots available but only 4 can be used by the A10.

Obviously fixable by changing aircraft although auto purchasing could do with not buying any more A10's! I can free up a user space by creating an extra user flight that isn't flown. That seems to work.

**Comment by Starfire13** [comment] 2021-02-17 19:53
Yep, this is a known issue with the Syria map. At Al Dumayr, I find that even restricting A-10s to just 5 (there are 5 parking spots they can fit in) is not sufficient to avoid the problem as DCS does not prioritise those slots for the A-10s. What I do is make sure that every single A-10 at Al Dumayr is set up for a mission, and are all set to air start. It's a clunky way to avoid the issue, for now.

**Comment by DanAlbert** [comment] 2021-06-05 02:29
Duplicate of #371

**Closed as completed by DanAlbert** 2021-06-05 02:29 UTC
Labels: bug, dcs issue
