### ISSUE TITLE
"Could not find front line point 5000 from Dededo" Error

### ISSUE THREAD

**Issue by EatenOrpheus30** [dcs-liberation/dcs_liberation#2450] opened 2022-09-20 21:46 UTC
### Affected versions

5.2.0

### Description

Got the error after cheat-capturing Adacao, Dededo, and Yigo in the Landing at Agat campaign on Marianas. In the sortie I did before I got the error, I killed 3 enemy tanks that were at Adacao. When I captured Adacao, it had 0 enemy units; when I captured Dededo, it had 1 enemy unit; and when I captured Yigo, it had 1 enemy unit (I think it was the same unit that was at Dededo, it just moved to Yigo when I captured Dededo).

Here's the exact error I got:
![image](https://user-images.githubusercontent.com/114030021/191370058-8bb06e0a-7274-4b7d-ac75-b8c356cf24ce.png)

### Save game and other files

[Bug Report.zip](https://github.com/dcs-liberation/dcs_liberation/files/9611460/Bug.Report.zip)

**Comment by Starfire13** [comment] 2022-09-20 21:54
For reference, a fix was previously attempted but made things worse and was reverted.

https://github.com/dcs-liberation/dcs_liberation/issues/1912 and https://github.com/dcs-liberation/dcs_liberation/pull/1914

**Comment by DanAlbert** [comment] 2022-09-20 22:26
Duplicate of #1784

**Closed as not planned by DanAlbert** 2022-09-20 22:26 UTC
Labels: bug
