### ISSUE TITLE
units listed as available but they are not

### ISSUE THREAD

**Issue by Tinchus2009** [dcs-liberation/dcs_liberation#1462] opened 2021-07-26 00:29 UTC
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
As an example, i have chosen a new campaign: operation mole cricket. in the blue colaition it is listed the JF-17 as available to the player (I have that module). Once the wizard has finished, the JF-17 is not available to the player.

**To Reproduce**

**Expected behavior**

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

- DCS Liberation save file (the `.liberation` file you save from the DCS Liberation window). By default these are located in your DCS saved games directory (`%USERPROFILE%/Saved Games/DCS`).
- The generated mission file (the `.miz` file that you load in DCS to play the turn). By default these are located in your missions directory (`%USERPROFILE%/Saved Games/DCS/Missions`).
- A tacview track file, especially when demonstrating an issue with AI behavior. By default these are located in your Tacview tracks directory (`%USERPROFILE%/Documents/Tacview`).
- The state.json file from the finished mission when the problem is related to results processing. By default these are located in your Liberation install directory.

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.3.1]: 4.0

**Additional context**

**Comment by DanAlbert** [comment] 2021-07-26 01:20
No info, nothing we can do.

**Comment by DanAlbert** [comment] 2021-07-26 01:21
> in the blue colaition

Which one? Do you mean bluefor modern?

**Comment by Tinchus2009** [comment] 2021-07-26 01:34
yes

**Comment by Tinchus2009** [comment] 2021-07-26 01:37
ait... I hve found a nice bug, give me a couple of minutes to write how to reproduce

**Comment by Tinchus2009** [comment] 2021-07-26 01:42
Do this: 
NEW GAME
Select the campaign Operation Mole cricket 2010 an click next: you will sea bluefor modern as player faction and Syria 2011 as enenmy
Click BACK and mark "ÏNVERT MAP" and click next
Now player faction RUSSIA 2010 and enemy is USA 1990

**Comment by bgreman** [comment] 2021-07-27 21:32
@Tinchus2009  That should be filed as a separate bug to keep this one on topic.

**Comment by bgreman** [comment] 2021-07-27 21:39
@Tinchus2009 I cannot reproduce the original described behavior in either the 4.0.0 release build nor the latest 4.x preview build.  If I choose Bluefor Modern on that campaign, I am able to purchase JF-17s as expected, and the AI plans missions for them as normal.

If what you mean is that you discovered that what was actually happening was the latter reported behavior was changing you to a faction that didn't have the JF-17, then this bug should be closed and a new one opened to handle that issue.  Please advise.

**Comment by Mustang-25** [comment] 2021-07-29 16:29
> Do this:
> NEW GAME
> Select the campaign Operation Mole cricket 2010 an click next: you will sea bluefor modern as player faction and Syria 2011 as enenmy
> Click BACK and mark "ÏNVERT MAP" and click next
> Now player faction RUSSIA 2010 and enemy is USA 1990

I am the campaign author and I never set up the invert map option (and don't intend to, tbh). So I do not recommend trying anything with inverting my campaigns.

**Comment by Tinchus2009** [comment] 2021-07-29 18:38
@bgreman then yes, this should be reported like that
@Mustang-25 I dont know and I guess no user can know what settings did you offer in the campaign. The real this is that when you choose the campaign the invert map option is there and nothing stops you selecting that option. And to be sincere most players will choose since the blue force is very unrealistic and the disadvantage it creates makes the campaign so boring (how do you expect to be fun when your side has all moder aircrafts and the other side has barely some few planes that can even stand against an A10...

**Comment by bgreman** [comment] 2021-07-29 18:47
It is possible to just reverse the factions without inverting the map.

**Comment by bgreman** [comment] 2021-07-29 18:49
@Tinchus2009 please open a new bug describing the behavior where the factions revert if you move backward in the new game wizard.  I am closing this bug as it is not reproducible from the files given.

**Closed as completed by bgreman** 2021-07-29 18:49 UTC
Labels: bug, not reproducible
