### ISSUE TITLE
Trying to frag missions from carrier: "Could not find any airfield assigned to this package"

### ISSUE THREAD

**Issue by jeetsukumaran** [dcs-liberation/dcs_liberation#1254] opened 2021-06-18 10:34 UTC
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**

Cannot generate sorties from any carrier based squadron. We are told: "Could not find any airfield assigned to this package."

**To Reproduce**
1. Click on any icon to call up mission generation dialog.
2. Create any mission, but select carrier-based aircraft to carry it out.

**Expected behavior**

Missions can be scheduled using carrier aircraft.

**Additional information**

```
Traceback (most recent call last):
  File "windows\mission\flight\QFlightCreator.py", line 227, in on_aircraft_changed
  File "widgets\combos\QOriginAirfieldSelector.py", line 39, in change_aircraft
  File "widgets\combos\QOriginAirfieldSelector.py", line 44, in rebuild_selector
  File "game\theater\controlpoint.py", line 967, in can_operate
AttributeError: 'NoneType' object has no attribute 'carrier_capable'
2021-06-18 03:27:17,643 :: ERROR :: Could not create flight
Traceback (most recent call last):
  File "windows\mission\QPackageDialog.py", line 186, in add_flight
  File "gen\flights\flightplan.py", line 909, in populate_flight_plan
  File "gen\flights\flightplan.py", line 995, in regenerate_package_waypoints
  File "gen\flights\flightplan.py", line 1040, in preferred_join_point
  File "gen\flights\flightplan.py", line 1941, in package_airfield
gen.flights.flightplan.PlanningError: Could not find any airfield assigned to this package
Traceback (most recent call last):
  File "windows\mission\flight\QFlightCreator.py", line 227, in on_aircraft_changed
  File "widgets\combos\QOriginAirfieldSelector.py", line 39, in change_aircraft
  File "widgets\combos\QOriginAirfieldSelector.py", line 44, in rebuild_selector
  File "game\theater\controlpoint.py", line 967, in can_operate
AttributeError: 'NoneType' object has no attribute 'carrier_capable'
2021-06-18 03:27:42,015 :: ERROR :: Could not create flight
Traceback (most recent call last):
  File "windows\mission\QPackageDialog.py", line 186, in add_flight
  File "gen\flights\flightplan.py", line 909, in populate_flight_plan
  File "gen\flights\flightplan.py", line 995, in regenerate_package_waypoints
  File "gen\flights\flightplan.py", line 1040, in preferred_join_point
  File "gen\flights\flightplan.py", line 1941, in package_airfield
gen.flights.flightplan.PlanningError: Could not find any airfield assigned to this package
Traceback (most recent call last):
  File "windows\mission\flight\QFlightCreator.py", line 227, in on_aircraft_changed
  File "widgets\combos\QOriginAirfieldSelector.py", line 39, in change_aircraft
  File "widgets\combos\QOriginAirfieldSelector.py", line 44, in rebuild_selector
  File "game\theater\controlpoint.py", line 967, in can_operate
AttributeError: 'NoneType' object has no attribute 'carrier_capable'
QLayout: Attempting to add QLayout "" to QLoadoutEditor "", which already has a layout
Traceback (most recent call last):
  File "windows\mission\flight\QFlightCreator.py", line 227, in on_aircraft_changed
  File "widgets\combos\QOriginAirfieldSelector.py", line 39, in change_aircraft
  File "widgets\combos\QOriginAirfieldSelector.py", line 44, in rebuild_selector
  File "game\theater\controlpoint.py", line 967, in can_operate
AttributeError: 'NoneType' object has no attribute 'carrier_capable'
2021-06-18 03:28:35,329 :: ERROR :: Could not create flight
Traceback (most recent call last):
  File "windows\mission\QPackageDialog.py", line 186, in add_flight
  File "gen\flights\flightplan.py", line 909, in populate_flight_plan
  File "gen\flights\flightplan.py", line 995, in regenerate_package_waypoints
  File "gen\flights\flightplan.py", line 1040, in preferred_join_point
  File "gen\flights\flightplan.py", line 1941, in package_airfield
gen.flights.flightplan.PlanningError: Could not find any airfield assigned to this package
Traceback (most recent call last):
  File "windows\mission\flight\QFlightCreator.py", line 227, in on_aircraft_changed
  File "widgets\combos\QOriginAirfieldSelector.py", line 39, in change_aircraft
  File "widgets\combos\QOriginAirfieldSelector.py", line 44, in rebuild_selector
  File "game\theater\controlpoint.py", line 967, in can_operate
AttributeError: 'NoneType' object has no attribute 'carrier_capable'
2021-06-18 03:29:44,454 :: INFO :: Saving game
2021-06-18 03:29:59,333 :: ERROR :: Could not create flight
Traceback (most recent call last):
  File "windows\mission\QPackageDialog.py", line 186, in add_flight
  File "gen\flights\flightplan.py", line 909, in populate_flight_plan
  File "gen\flights\flightplan.py", line 995, in regenerate_package_waypoints
  File "gen\flights\flightplan.py", line 1040, in preferred_join_point
  File "gen\flights\flightplan.py", line 1941, in package_airfield
gen.flights.flightplan.PlanningError: Could not find any airfield assigned to this package
```

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.3.1]: Build 1971

**Comment by Hornet2041** [comment] 2021-06-18 17:48
#1258

**Comment by DanAlbert** [comment] 2021-06-18 22:43
Duplicate of #1258

**Closed as completed by DanAlbert** 2021-06-18 22:43 UTC
Labels: bug
