### ISSUE TITLE
Could DCS Airbase aircraft inventory be controlled from Liberation?

### ISSUE THREAD

**Issue by DKobi** [dcs-liberation/dcs_liberation#1796] opened 2021-11-24 14:38 UTC
Would it be possible to implement a feature where number of airframes available in a given Liberation generated DCS mission was set per airfield based on the actual inventory available in your Liberation campaign?

The reason I ask is that I use DCS Liberation to run large multiplayer campaigns. And having endless respawns within a round, only to have exceeded the amount of actual airframes available is very immersion breaking. Not to mention a bad respawn culture it can produce.

Please don't answer this request with a "But you can just tell your pilots not to respawn." Because I DO want them to respawn in many Liberation missions - IF we have available airframes AND the situation calls for it.

It would be really nice to have the impact of consequences with a campaign and campaign logistics/losses brought all the way into the DCS Sim. It is possible to do this manually, but it's a large undertaking every time. If it was possible to script it when you generate the mission it would be sooooo sweet.

**Comment by DanAlbert** [comment] 2021-11-26 21:14
Duplicate of #138

**Closed as completed by DanAlbert** 2021-11-26 21:14 UTC
Labels: enhancement
