### ISSUE TITLE
[Build 1971] AI Purchaser/Planner will not Utilize CVN and LHA

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#1260] opened 2021-06-18 17:43 UTC
**Describe the bug**
The Ai planner will not purchase aircraft for the CVN and LHA even if it has the money to do so. Further, even if the player manually purchases units there, the AI tasker will not generate any flights from the CVN and LHA.

**To Reproduce**
1. Generate a campaign
2. set max starting budget and auto-purchase on
3. Note how no units are purchased at the CVN and LHA
4. Optionally, manually purchase units on the carriers
5. Pass Turn 0 into Turn 1
6. Note that even when manually purchased, carrier aircraft receive no taskings

**Expected behavior**

**Additional information**

This behavior is especially obvious on the Battle for the UAE campaign where the player only starts with a single land base and the two carriers. Even at the default budget, you can see that Liwa AB will fill up and there will be leftover budget.

I believe this might also be the contributing factor to #1259 as the AWACS are probably at the bottom of the purchasing priority list so there isn't enough space at Liwa for the AI to purchase it. This could also be related to #1258?

**Additional context**
Illustrative save attached here:

[Build 1971 AI Purchaser Bug.zip](https://github.com/dcs-liberation/dcs_liberation/files/6678558/Build.1971.AI.Purchaser.Bug.zip)

**Comment by Hornet2041** [comment] 2021-06-18 17:48
#1258

**Comment by DanAlbert** [comment] 2021-06-18 22:43
Duplicate of #1258

**Closed as completed by DanAlbert** 2021-06-18 22:43 UTC
Labels: bug
