### ISSUE TITLE
All enemy AI planes crash on startup

### ISSUE THREAD

**Issue by rjv6261** [dcs-liberation/dcs_liberation#2760] opened 2023-03-15 15:43 UTC
### Affected versions

6.1.1

### Build information

Using premade Syrian campaign but have had this happen on every map in every campaign. Version 6.1.1. Didnt change anything it just changed one day.

### Description

When I unpause the mission after loading in and getting in module cockpit. Literally every airplane on the enemy side decides to just die, so in the first mission of every campaign I kill 25 flankers in 1 second.

### Save game and other files

[report.zip](https://github.com/dcs-liberation/dcs_liberation/files/10981906/report.zip)

**Comment by sturmalex** [comment] 2023-03-24 05:36
I took a look at the file because I am experiencing the same issues. 

According to the PyDCS file Marj Ruhayyil has 33 spawnpoints with **airplanes=True** and 20 spawnpoints with **airplanes=False**. (The 20 are some spawnpoints that are exclusively for helicopters.)
Liberation will let you buy 53 Aircraft at that Airfield. 
What happens on mission start is: DCS realizes the places beyond the 33 are for helos only and spawn the aircrafts in the air. That wouldnt be a issue - planes are made to fly, but to their demise **some of them** spawn in each other - and lawndart into the ground. 


![Image](https://user-images.githubusercontent.com/13836400/227433110-52c21cde-5d15-4fb0-8887-7fffcbcf0c5e.png)


![Image](https://user-images.githubusercontent.com/13836400/227431706-439c5062-90f3-4042-9209-dabb6704e4cc.png)

Some others are spawnin circiling in the air above the airfield:


![Image](https://user-images.githubusercontent.com/13836400/227432959-d2e1e65f-ee73-4701-9a63-11fe7176d9bb.png)


I suggest using the flag to reduce the number of maximum Airframes on an airport to the number of spawns with "airplanes=True" flag. This would be a quick fix to solve this issue. 

The issue on too small hangars for some planes can be worked around by the user (move squadrons with big planes to a different, bigger airport like Damascus)

The downside of this fix would be this would reduce the number of total airframes possible at the location if one would like to use a mixed assortment of planes and helicopters but its far better than to have a huge chunk of the enemy planes just crash.


I wrote a small text in the Bugsection on Discord yesterday.

**Comment by rjv6261** [comment] 2023-03-24 05:46
> I took a look at the file because I am experiencing the same issues.
> 
> According to the PyDCS file Marj Ruhayyil has 33 spawnpoints with **airplanes=True** and 20 spawnpoints with **airplanes=False**. (The 20 are some spawnpoints that are exclusively for helicopters.) Liberation will let you buy 53 Aircraft at that Airfield. What happens on mission start is: DCS realizes the places beyond the 33 are for helos only and spawn the aircrafts in the air. That wouldnt be a issue - planes are made to fly, but to their demise **some of them** spawn in each other - and lawndart into the ground.
> 
> ![Image](https://user-images.githubusercontent.com/13836400/227433110-52c21cde-5d15-4fb0-8887-7fffcbcf0c5e.png)
> 
> ![Image](https://user-images.githubusercontent.com/13836400/227431706-439c5062-90f3-4042-9209-dabb6704e4cc.png)
> 
> Some others are spawnin circiling in the air above the airfield:
> 
> ![Image](https://user-images.githubusercontent.com/13836400/227432959-d2e1e65f-ee73-4701-9a63-11fe7176d9bb.png)
> 
> I suggest using the flag to reduce the number of maximum Airframes on an airport to the number of spawns with "airplanes=True" flag. This would be a quick fix to solve this issue.
> 
> The issue on too small hangars for some planes can be worked around by the user (move squadrons with big planes to a different, bigger airport like Damascus)
> 
> The downside of this fix would be this would reduce the number of total airframes possible at the location if one would like to use a mixed assortment of planes and helicopters but its far better than to have a huge chunk of the enemy planes just crash.
> 
> I wrote a small text in the Bugsection on Discord yesterday.

Thank you for posting a firm explanation with proof. If the flag needs to be set to true where would I find the file that needs to be edited for that change. I’m okay with maxing out an airport because honestly the more planes the better. I figured it was a collision because sometimes the log would have something like “Red Su-33 killed Red Su-27”.

**Comment by sturmalex** [comment] 2023-03-24 05:47
Well I am no Developer(for Liberation anyways) but I believe this is not something the user can do. Basically the calculation for how many planes are allowed at an airfield needs to be adjusted and thats somewhere within Liberation.

**Comment by Starfire13** [comment] 2023-03-24 05:55
Yeah, this is a commonly encountered issue with that specific campaign because of its use of that airfield. One temporary workaround is to not give the enemy any airplane squadrons at that airfield.

**Comment by sturmalex** [comment] 2023-03-24 06:03
> Yeah, this is a commonly encountered issue with that specific campaign because of its use of that airfield. One temporary workaround is to not give the enemy any airplane squadrons at that airfield.

When looking at the pydcs Syria file, there are 247 entries of "airplanes=false" (and 1458 = true, for reference ) so I suppose this is not limited to Marj but its less apparent on e.g. Beirut because there are only 3 of 46 slots exclusive to helicopters.

**Comment by rjv6261** [comment] 2023-03-24 06:04
> > Yeah, this is a commonly encountered issue with that specific campaign because of its use of that airfield. One temporary workaround is to not give the enemy any airplane squadrons at that airfield.
> 
> When looking at the pydcs Syria file, there are 247 entries of "airplanes=false" (and 1458 = true, for reference ) so I suppose this is not limited to Marj but its less apparent on e.g. Beirut because there are only 3 of 46 slots exclusive to helicopters.

Would playing on another map fix this issue?

**Comment by Starfire13** [comment] 2023-03-24 06:59
> > Yeah, this is a commonly encountered issue with that specific campaign because of its use of that airfield. One temporary workaround is to not give the enemy any airplane squadrons at that airfield.
> 
> 
> 
> When looking at the pydcs Syria file, there are 247 entries of "airplanes=false" (and 1458 = true, for reference ) so I suppose this is not limited to Marj but its less apparent on e.g. Beirut because there are only 3 of 46 slots exclusive to helicopters.

Pretty much, yeah. I actually edited my Syria campaign (Peace Spring) some time back to avoid this issue. As far as I'm aware, this is the sole airfield folks have reported this problem at.

**Comment by Starfire13** [comment] 2023-03-24 06:59
> > > Yeah, this is a commonly encountered issue with that specific campaign because of its use of that airfield. One temporary workaround is to not give the enemy any airplane squadrons at that airfield.
> 
> > 
> 
> > When looking at the pydcs Syria file, there are 247 entries of "airplanes=false" (and 1458 = true, for reference ) so I suppose this is not limited to Marj but its less apparent on e.g. Beirut because there are only 3 of 46 slots exclusive to helicopters.
> 
> 
> 
> Would playing on another map fix this issue?

It won't fix it, but it will avoid it.

**Comment by DanAlbert** [comment] 2023-03-24 18:08
Thanks a lot for the investigation! That's saves us quite a bit of time :)

We can't really follow the suggestion here until #1391 is complete. Limiting to the number of available plane spots would fix plane spawns, yes, but it would make heliports entirely unusable.

Duplicate of #1391.

**Closed as not planned by DanAlbert** 2023-03-24 18:08 UTC
Labels: bug
