### ISSUE TITLE
Red F14-A on Al Minhad crashing when opening wings in hangar

### ISSUE THREAD

**Issue by jojom4n** [dcs-liberation/dcs_liberation#438] opened 2020-11-24 00:31 UTC
In two missions on a row, when I entered the mission, red spawned 6 F14-A in Al Minhad but something happened in the parking lot, I received after a few seconds a message that a F14-A was hit, pilot and RIO ejected and no F14-A took off at last.

By looking at the track, I I can see the 6 red F14-A open their wings while in the (small) hangar and I think that one of them hit the hangar walls with its wings opened, because its right wing was broken and smoke was all around. The other 5 F14-A were fine but did not taxi though.

**Comment by DanAlbert** [comment] 2020-11-24 08:52
I don't think we have any say in when they extend their wings. Sounds like a DCS bug?

**Comment by Khopa** [comment] 2020-11-24 10:50
No we don't have any control over that.

I've done a few tests and I've been able to reproduce the issue in a custom made mission.

![image](https://user-images.githubusercontent.com/2546901/100083920-69a7e300-2e4a-11eb-8c3d-a3c6df2a60c9.png)

When they start taxying, they break their wing and stop : 

![image](https://user-images.githubusercontent.com/2546901/100084045-90661980-2e4a-11eb-8477-e95e9858613f.png)

This was the F-14A, but with the F-14B in the same slot, this works fine : 

![image](https://user-images.githubusercontent.com/2546901/100084245-cefbd400-2e4a-11eb-8749-c7126d84021f.png)

![image](https://user-images.githubusercontent.com/2546901/100084337-ef2b9300-2e4a-11eb-9f76-258cb353ebc3.png)

**In most cases, in tests i've done :**

AI F-14B will open their wings : When starting up their engines if the slot is big enough to allow it.
On entering the runway if their slots was not big enough to allow extending their wings.

AI F-14A seems to sometimes follow this behaviour, but not as well as the F-14B.

I'd say the bug is on Heatblur side. I will open a bug report on the forums.

**Comment by jojom4n** [comment] 2020-11-24 10:51
Wouldn't it be possible to prevent DCS Liberation to spawn them under the hangar?
And, besides that, when opening the mission in mission editor, can I assign them another parking lot to ramp start from or will DCS Liberation not appreciate that manual modification?

**Comment by Khopa** [comment] 2020-11-24 10:59
> Wouldn't it be possible to prevent DCS Liberation to spawn them under the hangar?

We generally prevent this from happening, as pydcs the library we use, will find compatible slots for the selected aircraft. And this slot is compatible in theory with the F-14A (As it is compatible for the F-14B), 

We could ultimately start listing which ones are causing issues, but this will be very hard and time consuming to maintain such a list.

> And, besides that, when opening the mission in mission editor, can I assign them another parking lot to ramp start from or will DCS Liberation not appreciate that manual modification?

Yes you can do that as a workaround for now, it will not cause issues to liberation.

**Comment by Khopa** [comment] 2020-11-24 11:02
For reference, miz file to reproduce issue : 

[f14a_taxi_issue_at_al_minhad.zip](https://github.com/Khopa/dcs_liberation/files/5589382/f14a_taxi_issue_at_al_minhad.zip)

**Comment by Khopa** [comment] 2020-11-24 11:07
ED Forums thread : https://forums.eagle.ru/forum/english/licensed-third-party-projects/heatblur-simulations/dcs-f-14a-b/bugs-and-problems-bf/7151390-taxi-issue-on-al-minhad-airbase-for-the-f-14a-135-gr

**Comment by Mustang-25** [comment] 2021-05-27 20:12
Just tested it with the miz file above. The problem seems to be resolved and the AI taxied out of the spot with the wings swept back. Going to close this one out.

**Closed as completed by Mustang-25** 2021-05-27 20:12 UTC
Labels: bug, dcs issue
