### ISSUE TITLE
Can't hit "take off" button when tanker flights are attached to packages

### ISSUE THREAD

**Issue by rhoadsy123** [dcs-liberation/dcs_liberation#2689] opened 2023-01-05 05:26 UTC
### Affected versions

6.0.0

### Build information

DCS Liberation 6.1.0

### Description

When attaching tankers to flight packages, they attach perfectly fine and then when I hit the take off button I receive this error message
![image](https://user-images.githubusercontent.com/109817780/210707602-6b166e35-305e-4358-8850-90329f3d9ff3.png)

### Save game and other files

[LIB Bug 1-4-23.zip](https://github.com/dcs-liberation/dcs_liberation/files/10349543/LIB.Bug.1-4-23.zip)

**Comment by Starfire13** [comment] 2023-01-05 20:58
Don't attach tankers to flight packages. Plan them on your carriers, or on a friendly airfield.

That said, yes the error should be fixed. Prior to 6.0, you could not attach tankers to packages.

Edit: In fact, you can plan refueling flights against any enemy unit (SAM sites, resource sites, armour groups, etc) in 6.1, which you could not do in 5.x. I suspect this is a bug.

**Comment by DanAlbert** [comment] 2023-01-05 21:12
This is 6 though, so that should work.

**Comment by Starfire13** [comment] 2023-01-05 21:18
Is it intended then that tankers should be plannable with any enemy unit as the target?

I see that you can, say, attach a refuel flight to a TARCAP package planned for a hostile SAM site. But you cannot attach a refuel flight to a BARCAP package planned for a friendly SAM site(because one is planned against an enemy target and one is planned against a friendly target).

**Comment by Starfire13** [comment] 2023-01-05 22:27
Having the ability to plan a tanker that is package specific (meaning only aircraft in that package would refuel from it) is actually very useful, though I don't know if that's the intent or even possible. For now at least, it doesn't appear that the auto planner will plan refuelling flights in a package with other flights, nor does it appear to plan refuelling flights with hostile units or airfields as the target (although the player can). One thing it can do that the player can't though, is plan a refuelling flight over a friendly FOB.

**Comment by DanAlbert** [comment] 2023-01-06 01:25
> you cannot attach a refuel flight to a BARCAP package

AI BARCAP (and anything that isn't vaguely strike-like, for that matter) will not use the package tankers, except maybe in emergencies?

> Having the ability to plan a tanker that is package specific (meaning only aircraft in that package would refuel from it) is actually very useful, though I don't know if that's the intent or even possible.

That's the idea behind the feature in 6.0. DCS AI will do as it pleases.

> it doesn't appear that the auto planner will plan refuelling flights

The autoplanner won't plan package refueling at all.

**Comment by Starfire13** [comment] 2023-01-06 01:58
> AI BARCAP (and anything that isn't vaguely strike-like, for that matter) will not use the package tankers, except maybe in emergencies?

In that case, why allow refuel flights to be plannable for TARCAPs since they also have no refuel waypoint?


> That's the idea behind the feature in 6.0. DCS AI will do as it pleases.

I see. At the moment it doesn't work since attaching a refuel flight to a package generates an error. You can plan a separate refuel flight package to the same target though. So the issue is when it's in the same package as another flight.

**Comment by DanAlbert** [comment] 2023-01-06 05:52
> In that case, why allow refuel flights to be plannable for TARCAPs since they also have no refuel waypoint?

You're not adding a refueling flight to a TARCAP. You're adding a refueling flight to a package that contains a TARCAP, and might also have other stuff.

**Comment by Starfire13** [comment] 2023-01-06 06:50
> You're not adding a refueling flight to a TARCAP. You're adding a refueling flight to a package that contains a TARCAP, and might also have other stuff.


Good point there.

**Comment by DanAlbert** [comment] 2023-01-28 20:14
Your save generates fine for me. I don't even know how you could possibly reach the error message that's being shown here, because that's the code path for aborting a flight that's in progress, which can only happen by hitting the "cancel/abort" button for a package/flight, not the "take off" button.

I've tried a whole lot of things (generating; deleting flights; generating then deleting flights; enabling fast forward and deleting flights; enabling fast forward, generating, then deleting flights; etc) and was not manage to make this bug appear. Either the save that was uploaded is not the right save, the instructions are incomplete, or this bug is not reproducible. In any case, we can't do anything until one of those three things changes.

**Closed as not planned by DanAlbert** 2023-01-28 20:14 UTC
Labels: bug
