### ISSUE TITLE
UI Elements in the liberation client cant be clicked or are very delayed

### ISSUE THREAD

**Issue by Firedown35** [dcs-liberation/dcs_liberation#416] opened 2020-11-21 10:16 UTC
I'm not sure if it only happens to me but whenever I try to click on something like for example if I want to edit a flight, take off or do anything similar, clicking is very delayed or requires multiple clicks (15 - 20 times). Sometimes the buttons just stop working.

**Comment by DanAlbert** [comment] 2020-11-21 11:50
It's a common problem. The UI framework we use isn't processing mouse clicks every time for some reason.

**Comment by Firedown35** [comment] 2020-11-21 13:20
> 
> 
> It's a common problem. The UI framework we use isn't processing mouse clicks every time for some reason.

is it something that can be fixed or is it just how it's going to be for now?

**Comment by Boozdeuvash** [comment] 2020-11-21 21:22
I think it's a click position problem, I've noticed that they always register when i click on the text of the button, but never when i click on an empty space of the button. Note that not all buttons have this issue, the Edit and Delete button in the packages and flights panel on the left are a notable exception.

So it seems that always clicking on the text of the button is an effective workaround, albeit a tedious one.

using v2.2.1 btw

**Comment by DanAlbert** [comment] 2020-11-21 21:57
> > It's a common problem. The UI framework we use isn't processing mouse clicks every time for some reason.
> 
> is it something that can be fixed or is it just how it's going to be for now?

My suspicion is that Qt is missing clicks because we only have the one thread and it's doing too much work to generate the UI, and for some reason is refreshing the UI quite frequently even though there are no changes. The fix is to offload the heavy work onto another thread, which is a large undertaking.

If I'm right about that, it's a significant enough amount of work that we might as well just redo the UI, since none of us are very fond of the current system anyway (and it would pave the way for us making a multi-user mission planner).

If there were easy fixes they'd get done right away because the problem is extremely annoying during development as well, but so far there don't appear to be any.

**Comment by DanAlbert** [comment] 2020-11-22 09:17
@Boozdeuvash is right. The text is a valid click location and the rest of the button isn't. That's... extremely strange.

**Comment by DanAlbert** [comment] 2021-01-01 23:46
It's the theming. Reverting to the vanilla theme (file -> settings) fixes the problem.

Rules like this don't work:

```
QPushButton[style="start-button"]{
    padding: 8px 30px;
}
```

The padding is not a clickable part of the button.

**Comment by DanAlbert** [comment] 2021-01-01 23:52
Was a Qt bug: https://bugreports.qt.io/browse/QTBUG-86587. Updating to the latest version of pyside2 fixes it. Should already be fixed in recent builds, but I've pushed a fix to update our minimum requirements.

**Closed as completed** 2021-01-01 23:51 UTC
