### ISSUE TITLE
Enemy QRF flights for Airbases

### ISSUE THREAD

**Issue by rhoadsy123** [dcs-liberation/dcs_liberation#3248] opened 2023-11-18 20:13 UTC
**Is your feature request related to a problem? Please describe.**
Not really a problem, but basically airbases will have aircraft sitting on the ground when enemy aircraft fly over them, and nobody will scramble. That's perfect for OCA/Aircraft taskings, but also a bit weird looking as the runway will be operational and the enemy is effectively just letting you fly over their airbase and not doing anything about it.

**Describe the solution you'd like**
Having a trigger (maybe based on EWR detection???) that would send up maybe a flight or two to intercept any aircraft that are near the airbase as a QRF defense? Might be very complex to actually implement but could be cool to look into.

**Comment by Starfire13** [comment] 2023-11-18 20:35
Every airfield already has BARCAP to engage incoming attack aircraft. Ignoring the coding complexity, one issue with QRF is that ground pathing is pretty bad and flights have to be spread out to prevent this. Having some flight just slotted in dynamically can really jam up the airfield.

**Comment by rhoadsy123** [comment] 2023-11-18 20:42
That makes sense, I figured that's why you had the BARCAPs set up and I felt like it'd be a coding/airfield management issue.

**Comment by DanAlbert** [comment] 2023-11-18 22:02
Duplicate of #351

**Closed as not planned by DanAlbert** 2023-11-18 22:02 UTC
Labels: enhancement
