### ISSUE TITLE
Unable to finish campaign

### ISSUE THREAD

**Issue by ataribaby42** [dcs-liberation/dcs_liberation#1909] opened 2022-01-04 21:58 UTC
### Affected versions

5.0.0

### Description

After conquering last control point Aleppo, Liberation crashed with error during debriefing.

![Liberation-error](https://user-images.githubusercontent.com/54838824/148129326-2859f527-424a-44c9-8559-e5641199275e.jpg)

### Save game and other files

Savegame file with campaign defintions attached

[Liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/7810621/Liberation.zip)

**Comment by DanAlbert** [comment] 2022-01-04 23:34
Duplicate of https://github.com/dcs-liberation/dcs_liberation/issues/978

**Closed as completed by DanAlbert** 2022-01-04 23:34 UTC
Labels: bug

**Comment by ataribaby42** [comment] 2022-01-05 00:35
> Duplicate of #978

How is this duplicate? #978 is enhancement. I got bug that prevented me to continue.
