### ISSUE TITLE
Buy new vehicles menu display bug

### ISSUE THREAD

**Issue by 17721250181** [dcs-liberation/dcs_liberation#1043] opened 2021-04-29 11:25 UTC
**Describe the bug**

On my laptop, 1920*1080 and 125% zoom (windows's zoom in settings)
The menu for buying planes and vehicles can't display correctly, the plus and minus button are too far right and hidden.
As well as some founts are too thick to read, and too big for their box as well.
I've tried both DCS theme and vinilla theme
![新建位图图像 (2) - 副本](https://user-images.githubusercontent.com/60857118/116543432-f6972100-a941-11eb-9731-2cd15260359d.jpg)
![新建位图图像 - 副本](https://user-images.githubusercontent.com/60857118/116543443-fac33e80-a941-11eb-9d12-25212b3b7456.jpg)

**Version information (please complete the following information):**
 - DCS Liberation [2.5.0]:

**Additional context**

**Comment by Mustang-25** [comment] 2021-05-04 15:55
This seems to be the same problem as #887. That specific font just don't play well with the Liberation UI at this time.

**Comment by 17721250181** [comment] 2021-05-05 07:34
Can the font be changed manually?

**Comment by DanAlbert** [comment] 2021-06-05 02:16
Duplicate of #887.

**Closed as completed by DanAlbert** 2021-06-05 02:16 UTC
Labels: bug
