### ISSUE TITLE
Waypoint speed too low for AI

### ISSUE THREAD

**Issue by alexkrebiehl** [dcs-liberation/dcs_liberation#1045] opened 2021-04-30 01:20 UTC
**Describe the bug**
Target speed for a waypoint is too slow (114kts), and AI fall out of the sky and crash. The mission was not edited after being generated by Liberation.

**Expected behavior**
AI doesn't crash into mountain :)

**Additional information**

T+00:36:33 - T+00:40:00

Observed Flights:
- F18 PHEASANT DEAD|2|3|25
- F18 PHESANT DEAD|2|4|25

We will usually need more information for debugging. Include as much of the following as you are able:

- DCS Liberation save file (the `.liberation` file you save from the DCS Liberation window). By default these are located in your DCS saved games directory (`%USERPROFILE%/Saved Games/DCS`).
- The generated mission file (the `.miz` file that you load in DCS to play the turn). By default these are located in your missions directory (`%USERPROFILE%/Saved Games/DCS/Missions`).
- A tacview track file, especially when demonstrating an issue with AI behavior. By default these are located in your Tacview tracks directory (`%USERPROFILE%/Documents/Tacview`).
- The state.json file from the finished mission when the problem is related to results processing. By default these are located in your Liberation install directory.

**Version information (please complete the following information):**
 - DCS Liberation v2.5
[liberation AI crash.zip](https://github.com/Khopa/dcs_liberation/files/6402503/liberation.AI.crash.zip)

**Comment by alexkrebiehl** [comment] 2021-04-30 01:36
Also just noticed that my F16 HORSE BAI|2|19|31 flight (in the same mission) decides to split up before suddenly deciding to dive from 15k feet into the ground. Seems to be different than the above issue where the AI was going too slow to stay in the air.
[Tacview-20210428-212906-DCS-liberation_nextturn.zip.zip](https://github.com/Khopa/dcs_liberation/files/6402538/Tacview-20210428-212906-DCS-liberation_nextturn.zip.zip)

**Comment by DanAlbert** [comment] 2021-05-21 02:15
Duplicate of https://github.com/dcs-liberation/dcs_liberation/issues/774

The TOT for the egress point is set such that there's time for the AI to perform their attack. They can't find the target so they gave up, then flew slowly to try to reach their egress at the correct time :(

**Closed as completed by DanAlbert** 2021-05-21 02:15 UTC
Labels: bug
