### ISSUE TITLE
Aircraft that diverted disappearing

### ISSUE THREAD

**Issue by phoenixegmh** [dcs-liberation/dcs_liberation#962] opened 2021-03-25 09:43 UTC
Aircraft departed CVN with divert waypoint set. Aircraft diverted to the divert aerodrome and at end of turn, do not appear either back with the Squadron (to simulate being ferried back) or at the divert aerodrome. These units are essentially lost.

**Expected behavior**
Aircraft should either appear at the divert aerodrome or return to the squadron

**Additional information**

ZIP with state.json, Tacview file and post turn Liberation: https://file.io/IhWZWaMFUXfe

There were 12 Hornets at the CVN, 4 were shot down, 2 diverted. Liberation shows 6 remaining at CVN and 0 at Gudauta.

**Version information (please complete the following information):**
 - DCS Liberation 2.4.3
 -

**Comment by Mustang-25** [comment] 2021-07-16 00:39
Haven't seen this issue in my recent testing. Closing this one out but if the problem is still present on the latest release we can reopen it.

**Closed as completed by Mustang-25** 2021-07-16 00:39 UTC
Labels: bug
