### ISSUE TITLE
Ground units "burning"as in, having a yellow glow around them

### ISSUE THREAD

**Issue by Revinl** [dcs-liberation/dcs_liberation#169] opened 2020-10-02 13:22 UTC
-It affects certain ground units, for example; Abrams, Bradley, Stryker (might be more)
and others not, like the russian BMPs. 

-It is not continues, so it only happens when they move, or sometimes when they move, sometimes not when they move, very random. 

Might be a healthstate issue?

https://cdn.discordapp.com/attachments/595706079459934208/761576359864434758/unknown.png

https://cdn.discordapp.com/attachments/595706079459934208/761575116752551977/unknown.png

https://cdn.discordapp.com/attachments/595706079459934208/761574386117246976/unknown.png

For some reference pictures.

**Comment by Khopa** [comment] 2020-10-02 15:24
Thanks, I have experienced this issue randomly in the past too. 
What factions were you using for both side ? 

Closing the issue because a duplicate of this one : https://github.com/Khopa/dcs_liberation/issues/103


Khopa

**Closed as completed by Khopa** 2020-10-02 15:24 UTC
