### ISSUE TITLE
Helicopter specific tasking

### ISSUE THREAD

**Issue by entropyembrace** [dcs-liberation/dcs_liberation#1385] opened 2021-06-28 23:42 UTC
Before filing, please search the issue tracker to see if this feature has already been requested.

If requesting a DCS AI feature, check If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Is your feature request related to a problem? Please describe.**
Currently helicopters are given tasks with the same logic that is applied to jets leading to them attempting to fly at 20,000 feet to their assigned target and dropping sharply to low altitude to attempt to use their weapons.

**Describe the solution you'd like**
I'd like to see helicopter specific tasking so that helicopters are assigned waypoints with more sensible altitudes for their capabilities.

**Additional context**

**Comment by lizhaobei85032** [comment] 2021-06-29 04:32
朋友，请问你是怎么开始飞行的，我的4.0.0版本错误很多，无法点击TAKE OFF

**Comment by DanAlbert** [comment] 2021-06-29 07:39
Duplicate of #270

**Closed as completed by DanAlbert** 2021-06-29 07:39 UTC
Labels: enhancement

**Comment by magwo** [comment] 2021-08-04 09:58
This is now fixed. It was a bug that helicopters didn't have low-altitude waypoints. That said, helicopter flight planning could be improved further.
