### ISSUE TITLE
Report an error after capturing the last position

### ISSUE THREAD

**Issue by Pil-Nick** [dcs-liberation/dcs_liberation#2240] opened 2022-06-07 16:41 UTC
### Affected versions

5.2.0

### Description

After capturing the last point in the game, there is an error when submitting the result of the quest, and an error when starting the quest after canceling the quest. The error content is shown as follows:
![R@QTK~{U7(P$ 2ZC)~%41O3](https://user-images.githubusercontent.com/79027768/172434908-77acf38b-94f8-4ecf-82a8-f14a157e91a0.png)
![5Q88JLFKBQ9O_HJKH3YNZ@Q](https://user-images.githubusercontent.com/79027768/172434934-12fe19fe-1140-4ee5-9202-ff3ee7ec50d1.png)

### Save game and other files

[file.zip](https://github.com/dcs-liberation/dcs_liberation/files/8855033/file.zip)

**Comment by Raffson** [comment] 2022-06-08 16:53
The second exception is very obvious since the assertions state that `closest_blue` and `closest_red` are not allowed to be `None`. In case of a WIN/LOSS it should speak for itself that <ins>at least</ins> one of them will be `None` . The current code on the development branch suggests even both will be `None` . The solution seems straight forward, just delete the assertions and add checks wherever `closest_opposing_control_points` is called. Or am I missing something?
_EDIT: ok I see the tricky part, gonna try to figure a proper solution for it..._

As for the first exception, I'm assuming this got already fixed during refactoring since I haven't come across it. For the sake of thoroughness I'll try testing it "live" since I only tried reproducing this problem using cheat options.

**Comment by DanAlbert** [comment] 2022-06-08 19:00
Duplicate of #978

**Closed as not planned by DanAlbert** 2022-06-08 19:00 UTC
Labels: bug
