### ISSUE TITLE
Carrier Not Clickable

### ISSUE THREAD

**Issue by Bigs2013** [dcs-liberation/dcs_liberation#2388] opened 2022-08-25 21:17 UTC
### Affected versions

Development build

### Development build

4225

### Description

Carrier is no longer clickable after mission completion and moved to next turn

### Save game and other files

[Beta.zip](https://github.com/dcs-liberation/dcs_liberation/files/9428317/Beta.zip)

**Comment by Bigs2013** [comment] 2022-08-25 21:22
Resolved by giving move waypoint

**Comment by Starfire13** [comment] 2022-08-26 11:21
Carrier is clickable after mission completion. Marking as not reproducible and closing.

**Comment by Starfire13** [comment] 2022-08-28 12:22
Reopening as I've done some additional testing and have figured out how to replicate the bug. It only occurs if you have moved the carrier on the previous turn.

Test was performed using #4326. Save file attached.
[North Russia #4236 Turn 8.zip](https://github.com/dcs-liberation/dcs_liberation/files/9439633/North.Russia.4236.Turn.8.zip)

To replicate:
1. Move the carrier (leave the LHA alone).
2. Pass Turn.
3. Carrier can no longer be left-clicked on. LHA can.
4. In order to make the carrier movable once again, you have to right-click + drag it.

This may or may not be related to the problem but when the carrier (or LHA for that matter) is moved via right-click + drag, the mission package window opens once you release the right mouse button, so you have to close the window each time you move the carrier. It didn't use to do this.

**Comment by DanAlbert** [comment] 2022-10-08 00:52
This is the result of the immensely gross way we had to implement the carrier click-and-drag in the new map. We had to do it that way because of a bug in a dependency, which looks to be resolved, so it seems we can delete a bunch of code and fix the bug in the process.

**Comment by DanAlbert** [comment] 2022-10-08 04:39
Never mind, I misread a comment. This component needs to be rewritten, but I'm not sure how just yet.

**Closed as completed** 2022-10-09 23:25 UTC
Labels: bug
