### ISSUE TITLE
6.0 4060 - Same issue as previous bug report #2212

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-liberation/dcs_liberation#2301] opened 2022-07-05 06:30 UTC
### Affected versions

Development build

### Description

https://github.com/dcs-liberation/dcs_liberation/issues/2212
[4060error.zip](https://github.com/dcs-liberation/dcs_liberation/files/9043808/4060error.zip)

The aircraft are spawning and crashing. This is not the same issue as Syria. Syria airfields sometimes spawn empty planes in the air due to crappy parking space logic. The planes on Caucasus are just spawning low and hitting the ground. 

Tacview, save, mission file that generated tacview is included.

### Save game and other files

attached above

**Comment by DanAlbert** [comment] 2022-07-05 08:36
I'm confused. Is this a dup of #2212 or not?

**Comment by holyorangejuice** [comment] 2022-07-05 10:10
Yeah but ya'll closed the report and it went nowhere. I was just lucky I was able to save more information this time.

**Comment by DanAlbert** [comment] 2022-07-05 10:12
We reopen bugs when get the information we need. We close bugs we can't investigate.

Duplicate of #2212

**Closed as not planned by DanAlbert** 2022-07-05 10:12 UTC
Labels: bug
