### ISSUE TITLE
West Georgia campaign does not create missions to Kutaisi airfield

### ISSUE THREAD

**Issue by ssg-dev** [dcs-liberation/dcs_liberation#897] opened 2021-02-17 21:09 UTC
**Describe the bug**
When creating any mission directed to Kutaisi, be it OCA, TARCAP or whatever Liberation does not generate mission.

**To Reproduce**
1. Right Click Kutaisi and select New Package
2. Choose Attack airfield
3. Add Flight
4. Choose anykind of flight and any combination of planes
5. Notice that it won't generate Time Over Target, not even when checking ASAP.
6. Press Save
7. Notice it did not generate mission waypoints and Package TOT on left panel is 0. 

**Expected behavior**
Mission should be generated

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

DCS Liberation save included
[kutaisibug.zip](https://github.com/Khopa/dcs_liberation/files/5998617/kutaisibug.zip)
**Version information (please complete the following information):**
 - DCS Liberation v2.5-1201

**Additional context**
Log file of creating mission

Traceback (most recent call last):
  File "qt_ui\windows\mission\QPackageDialog.py", line 186, in add_flight
  File "gen\flights\flightplan.py", line 798, in populate_flight_plan
  File "gen\flights\flightplan.py", line 872, in regenerate_package_waypoints
  File "gen\flights\flightplan.py", line 916, in preferred_join_point
  File "game\navmesh.py", line 146, in shortest_path
ValueError: Origin point Point(-284887.375, 683858.71875) is outside the navmesh

**Comment by DanAlbert** [comment] 2021-03-13 21:46
Your save game isn't usable because it's using a custom faction that we don't have. I just fixed https://github.com/Khopa/dcs_liberation/issues/903 though and this is probably a duplicate of that. Closing on that assumption, if that's wrong lmk.

**Closed as completed by DanAlbert** 2021-03-13 21:46 UTC
Labels: bug
