### ISSUE TITLE
liberation_main.exe won't start

### ISSUE THREAD

**Issue by HubFly35** [dcs-liberation/dcs_liberation#3087] opened 2023-07-18 18:03 UTC
### Affected versions

8.1.0

### Description

Hi

Ever since Version 5.0 (including Version 5.1) my liberation_main.exe won't start. I get the Ukrainian Ghost of Kyiv Flag banner load, then a white page behind it. I check task manager and it says Liberation liberation_main.exe is not responding.  I tried several times do reinstall liberation and deactivate Bitdefender (and add exception) but nothing helps. Windows and dcs is up to Date. With version 4.1 it works without any Problem ther are only Problem with version 5.0 an above.

### Save game and other files (save game required, bugs without saves will be closed)

There is no saved file in the folder

**Comment by DanAlbert** [comment] 2023-07-19 04:43
Probable duplicate of https://github.com/dcs-liberation/dcs_liberation/issues/3035?

**Comment by HubFly35** [comment] 2023-07-20 17:49
agreed...very similar but when I run mine as admin it still doesn't work. Any other ideas or suggestions?

**Comment by DanAlbert** [comment] 2023-07-20 20:36
Unfortunately no. No developer has ever been able to repro these problems so there's nothing for us to debug, and the usual suggestions didn't work. Corrupt Liberation install is the most common. Antivirus/firewall is the second most common problem I think. Admin (which really shouldn't be required, most people don't need it) is third. I don't think we've seen any other fixes.

Closing since we don't have more ideas for how to help, but anyone with ideas can of course still chime in.

**Closed as not planned by DanAlbert** 2023-07-20 20:36 UTC
Labels: bug
