### ISSUE TITLE
Could U bring in the localization function?(I can handle the CN translation)

### ISSUE THREAD

**Issue by foxwxl** [dcs-liberation/dcs_liberation#378] opened 2020-11-17 01:39 UTC
Hi, fantastic job for this project.  I've played DCS and BMS for decades, and for years I'm waiting for some kind of dynamic campaign engine in DCS just like this one. And this master piece has very much great potentials, hope U guys can bring us more and more interesting features.

What I am asking is whether U can bring in the localization function? I'm from DIS tester team, and U know, many people from China can not handle full english software well. I think its a good option if U can bring the project into chinese which will greatly help expanding the users.

Of course I can handle the Simplify Chinese translation if U needed.  I've done this for LOTATC, X4(a space sim game), etc.

THX.

**Comment by DanAlbert** [comment] 2020-11-17 06:21
Duplicate of https://github.com/Khopa/dcs_liberation/issues/82

**Closed as completed by DanAlbert** 2020-11-17 06:21 UTC
