### ISSUE TITLE
TGO SAM replacement doesn't update on map

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#2070] opened 2022-03-12 13:52 UTC
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1972037759

### Description

![image](https://user-images.githubusercontent.com/55866858/158020636-24ac299e-1f7c-4803-b74d-cbe988489de4.png)

Replaced the SAM unit at PORPOISE with an SA-10 (instead of SA-13). On the older versions (before the map backend changes?) this would update instantaneously on the map. Now it only shows its new state when you click on it. The map still shows old units plus its old threat circle.

### Save game and other files

[3627 check.zip](https://github.com/dcs-liberation/dcs_liberation/files/8237705/3627.check.zip)

note: this appears to affect all TGOs. also updates when turn is passed

**Comment by DanAlbert** [comment] 2022-03-12 19:23
Duplicate of #2047

**Closed as completed by DanAlbert** 2022-03-12 19:23 UTC
Labels: bug, UX
